#!/usr/bin/env bash
# RestaurantOS deploy step 2/4 -- generate every production secret ON
# this box, write the repo-root .env docker-compose.prod.yml reads.
#
# Nothing here is copied from services/api/.env.example, this repo's git
# history, or any dev/rehearsal environment -- every value is freshly
# generated by this script, right now, on this machine. Never commit the
# resulting .env (already excluded -- see .gitignore).
#
# Usage (run from the repo root, e.g. /opt/restaurantos):
#   ./scripts/deploy/02_generate_secrets.sh [--acme-email you@example.com]
#
# --acme-email is optional. If omitted, a placeholder is written to .env
# and the script prints a loud reminder to edit it before starting Caddy
# -- Let's Encrypt uses this address only for expiry/problem notices, it
# is never published, but Caddy needs *some* value to start.
#
# Safe to re-run: refuses to overwrite an existing .env unless you
# explicitly remove it first (regenerating the DB password after
# postgres has already initialized with the old one would lock the API
# out -- this is a deliberate guard, not an oversight).

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$REPO_DIR/.env"
ACME_EMAIL="CHANGEME@prashanthai.com"

while [ $# -gt 0 ]; do
    case "$1" in
        --acme-email)
            ACME_EMAIL="$2"
            shift 2
            ;;
        *)
            echo "Unknown argument: $1" >&2
            exit 1
            ;;
    esac
done

if [ -f "$ENV_FILE" ]; then
    echo "ERROR: $ENV_FILE already exists -- refusing to overwrite." >&2
    echo "Regenerating secrets after postgres has already initialized with the old" >&2
    echo "DATABASE_PASSWORD will lock the API out. If you really mean to start over" >&2
    echo "on a fresh box, remove $ENV_FILE (and the postgres_data volume, if it was" >&2
    echo "ever started) first." >&2
    exit 1
fi

echo "==> Generating DATABASE_PASSWORD"
DATABASE_PASSWORD="$(openssl rand -base64 32)"

echo "==> Generating a fresh RS256 JWT keypair for this deployment"
key_dir="$(mktemp -d)"
trap 'rm -rf "$key_dir"' EXIT
openssl genrsa -out "$key_dir/jwt_private.pem" 2048 2>/dev/null
openssl rsa -in "$key_dir/jwt_private.pem" -pubout -out "$key_dir/jwt_public.pem" 2>/dev/null
JWT_PRIVATE_KEY="$(cat "$key_dir/jwt_private.pem")"
JWT_PUBLIC_KEY="$(cat "$key_dir/jwt_public.pem")"

if [ "$ACME_EMAIL" = "CHANGEME@prashanthai.com" ]; then
    echo "WARNING: no --acme-email given -- writing a placeholder. Edit $ENV_FILE's" >&2
    echo "CADDY_ACME_EMAIL before running 'docker compose up -d caddy'." >&2
fi

echo "==> Writing $ENV_FILE"
cat > "$ENV_FILE" <<EOF
# Generated $(date -u +%Y-%m-%dT%H:%M:%SZ) by scripts/deploy/02_generate_secrets.sh.
# Every secret below was generated on this box -- never copied from this
# repo's history or a dev environment. Do not commit this file.

APP_ENV=production

DATABASE_USER=restaurantos
DATABASE_NAME=restaurantos
DATABASE_PASSWORD=${DATABASE_PASSWORD}

JWT_PRIVATE_KEY="${JWT_PRIVATE_KEY}"
JWT_PUBLIC_KEY="${JWT_PUBLIC_KEY}"

CORS_ALLOWED_ORIGINS=https://admin.prashanthai.com
NEXT_PUBLIC_API_BASE_URL=https://api.prashanthai.com

CADDY_ACME_EMAIL=${ACME_EMAIL}
EOF

chmod 600 "$ENV_FILE"

echo "==> Done. $ENV_FILE written and chmod 600."
if [ "$ACME_EMAIL" = "CHANGEME@prashanthai.com" ]; then
    echo "REMINDER: edit CADDY_ACME_EMAIL in $ENV_FILE before starting caddy."
fi
echo "Next: scripts/deploy/03_migrate.sh"
