"""The canonical set of ISO 4217 currency codes this platform accepts.

**Why this exists.** A tenant was created with `default_currency_code =
"GST"` -- not a currency at all (it's a tax), and nothing in the stack
caught it: the admin-web form only checked "3 uppercase letters", the
API's own request schema only checked length (`min_length=3,
max_length=3`), and the `tenants` table's own CHECK constraint only
checked the same regex (`~ '^[A-Z]{3}$'`) -- three independent "shape,
not membership" checks that all happily agree "GST" looks fine. This
module is the one real fix: an actual list of valid codes, used by the
request schema's own validator (see `tenant_schemas.py`) and mirrored
into the `tenants` table's CHECK constraint by a dedicated migration, so
neither layer can be bypassed independently.

**Sourced from ISO 4217's own active-code list** (verified against
Wikipedia's maintained table, cross-checked against known circulating
currencies), **deliberately excluding 11 codes that are real ISO 4217
entries but not something a tenant would ever price a menu in**:
precious metals (`XAU` gold, `XAG` silver, `XPD` palladium, `XPT`
platinum), the IMF's Special Drawing Right (`XDR`, an accounting unit
for international reserves, not spendable), four defunct European
bond-market composite units (`XBA`, `XBB`, `XBC`, `XBD`), and the two
codes ISO 4217 itself defines as non-currencies (`XTS`, reserved for
testing; `XXX`, meaning "no currency involved"). Everything else in the
standard is kept, including several unusual-but-real settlement/index
units (e.g. `CLF` Chile's Unidad de Fomento, `MXV` Mexico's UDI) that
some real tenant, however rarely, could legitimately need.

**Kept in exactly one place on the backend** -- both
`OnboardTenantRequestSchema`'s validator and the CHECK constraint
migration import/reference this same dict, rather than each hand-
maintaining their own copy. `apps/admin-web/src/lib/iso4217.ts` mirrors
this list for the frontend dropdown (TypeScript can't import a Python
module) -- keep both in sync if this one ever changes, which, per ISO
4217's own multi-year release cadence, should be rare.
"""

from __future__ import annotations

ISO_4217_CURRENCIES: dict[str, str] = {
    "AED": "United Arab Emirates dirham",
    "AFN": "Afghan afghani",
    "ALL": "Albanian lek",
    "AMD": "Armenian dram",
    "AOA": "Angolan kwanza",
    "ARS": "Argentine peso",
    "AUD": "Australian dollar",
    "AWG": "Aruban florin",
    "AZN": "Azerbaijani manat",
    "BAM": "Bosnia and Herzegovina convertible mark",
    "BBD": "Barbados dollar",
    "BDT": "Bangladeshi taka",
    "BHD": "Bahraini dinar",
    "BIF": "Burundian franc",
    "BMD": "Bermudian dollar",
    "BND": "Brunei dollar",
    "BOB": "Boliviano",
    "BOV": "Bolivian Mvdol",
    "BRL": "Brazilian real",
    "BSD": "Bahamian dollar",
    "BTN": "Bhutanese ngultrum",
    "BWP": "Botswana pula",
    "BYN": "Belarusian ruble",
    "BZD": "Belize dollar",
    "CAD": "Canadian dollar",
    "CDF": "Congolese franc",
    "CHE": "WIR euro",
    "CHF": "Swiss franc",
    "CHW": "WIR franc",
    "CLF": "Unidad de Fomento",
    "CLP": "Chilean peso",
    "CNY": "Renminbi",
    "COP": "Colombian peso",
    "COU": "Unidad de Valor Real",
    "CRC": "Costa Rican colon",
    "CUP": "Cuban peso",
    "CVE": "Cape Verdean escudo",
    "CZK": "Czech koruna",
    "DJF": "Djiboutian franc",
    "DKK": "Danish krone",
    "DOP": "Dominican peso",
    "DZD": "Algerian dinar",
    "EGP": "Egyptian pound",
    "ERN": "Eritrean nakfa",
    "ETB": "Ethiopian birr",
    "EUR": "Euro",
    "FJD": "Fiji dollar",
    "FKP": "Falkland Islands pound",
    "GBP": "Pound sterling",
    "GEL": "Georgian lari",
    "GHS": "Ghanaian cedi",
    "GIP": "Gibraltar pound",
    "GMD": "Gambian dalasi",
    "GNF": "Guinean franc",
    "GTQ": "Guatemalan quetzal",
    "GYD": "Guyanese dollar",
    "HKD": "Hong Kong dollar",
    "HNL": "Honduran lempira",
    "HTG": "Haitian gourde",
    "HUF": "Hungarian forint",
    "IDR": "Indonesian rupiah",
    "ILS": "Israeli new shekel",
    "INR": "Indian rupee",
    "IQD": "Iraqi dinar",
    "IRR": "Iranian rial",
    "ISK": "Icelandic krona",
    "JMD": "Jamaican dollar",
    "JOD": "Jordanian dinar",
    "JPY": "Japanese yen",
    "KES": "Kenyan shilling",
    "KGS": "Kyrgyzstani som",
    "KHR": "Cambodian riel",
    "KMF": "Comoro franc",
    "KPW": "North Korean won",
    "KRW": "South Korean won",
    "KWD": "Kuwaiti dinar",
    "KYD": "Cayman Islands dollar",
    "KZT": "Kazakhstani tenge",
    "LAK": "Lao kip",
    "LBP": "Lebanese pound",
    "LKR": "Sri Lankan rupee",
    "LRD": "Liberian dollar",
    "LSL": "Lesotho loti",
    "LYD": "Libyan dinar",
    "MAD": "Moroccan dirham",
    "MDL": "Moldovan leu",
    "MGA": "Malagasy ariary",
    "MKD": "Macedonian denar",
    "MMK": "Myanmar kyat",
    "MNT": "Mongolian togrog",
    "MOP": "Macanese pataca",
    "MRU": "Mauritanian ouguiya",
    "MUR": "Mauritian rupee",
    "MVR": "Maldivian rufiyaa",
    "MWK": "Malawian kwacha",
    "MXN": "Mexican peso",
    "MXV": "Mexican Unidad de Inversion",
    "MYR": "Malaysian ringgit",
    "MZN": "Mozambican metical",
    "NAD": "Namibian dollar",
    "NGN": "Nigerian naira",
    "NIO": "Nicaraguan cordoba",
    "NOK": "Norwegian krone",
    "NPR": "Nepalese rupee",
    "NZD": "New Zealand dollar",
    "OMR": "Omani rial",
    "PAB": "Panamanian balboa",
    "PEN": "Peruvian sol",
    "PGK": "Papua New Guinean kina",
    "PHP": "Philippine peso",
    "PKR": "Pakistani rupee",
    "PLN": "Polish zloty",
    "PYG": "Paraguayan guarani",
    "QAR": "Qatari riyal",
    "RON": "Romanian leu",
    "RSD": "Serbian dinar",
    "RUB": "Russian ruble",
    "RWF": "Rwandan franc",
    "SAR": "Saudi riyal",
    "SBD": "Solomon Islands dollar",
    "SCR": "Seychelles rupee",
    "SDG": "Sudanese pound",
    "SEK": "Swedish krona",
    "SGD": "Singapore dollar",
    "SHP": "Saint Helena pound",
    "SLE": "Sierra Leonean leone",
    "SOS": "Somali shilling",
    "SRD": "Surinamese dollar",
    "SSP": "South Sudanese pound",
    "STN": "Sao Tome and Principe dobra",
    "SVC": "Salvadoran colon",
    "SYP": "Syrian pound",
    "SZL": "Swazi lilangeni",
    "THB": "Thai baht",
    "TJS": "Tajikistani somoni",
    "TMT": "Turkmenistan manat",
    "TND": "Tunisian dinar",
    "TOP": "Tongan pa'anga",
    "TRY": "Turkish lira",
    "TTD": "Trinidad and Tobago dollar",
    "TWD": "New Taiwan dollar",
    "TZS": "Tanzanian shilling",
    "UAH": "Ukrainian hryvnia",
    "UGX": "Ugandan shilling",
    "USD": "United States dollar",
    "USN": "United States dollar (next day)",
    "UYI": "Uruguay Peso en Unidades Indexadas",
    "UYU": "Uruguayan peso",
    "UYW": "Unidad previsional",
    "UZS": "Uzbekistani sum",
    "VED": "Venezuelan digital bolivar",
    "VES": "Venezuelan sovereign bolivar",
    "VND": "Vietnamese dong",
    "VUV": "Vanuatu vatu",
    "WST": "Samoan tala",
    "XAF": "CFA franc BEAC",
    "XCD": "East Caribbean dollar",
    "XOF": "CFA franc BCEAO",
    "XPF": "CFP franc",
    "XSU": "Sucre",
    "YER": "Yemeni rial",
    "ZAR": "South African rand",
    "ZMW": "Zambian kwacha",
    "ZWL": "Zimbabwean dollar",
}
