"""create identity schema (tenants, users, sessions)

Revision ID: 0001
Revises:
Create Date: 2026-08-07

Hand-written, not autogenerated (Data Architecture v2.0 SS7.1) — this
migration relies on partial unique indexes, CHECK constraints, RLS
policies, and a trigger function, none of which Alembic's autogenerate
reliably produces correctly.

Scope: tenants, users, sessions only. Role/Permission/RolePermission/
UserRole are deferred to a follow-up migration (see the accompanying
models.py module docstring for why).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql.naming import conv

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ULID_REGEX = r"^[0-9A-HJKMNP-TV-Z]{26}$"

# `conv(...)` marks a name as already fully resolved. Without it, the
# naming convention configured on Base.metadata (env.py's target_metadata)
# re-applies its "ck_%(table_name)s_%(constraint_name)s" template to
# CheckConstraint names even when one is explicitly given, treating the
# given string as the raw %(constraint_name)s token — silently producing
# doubled names like "ck_tenants_ck_tenants_id_is_valid_ulid". Verified
# against `alembic upgrade head --sql` output; PrimaryKeyConstraint and
# ForeignKeyConstraint were not observed to double under the same
# convention, but are wrapped too for consistency and to avoid depending
# on that being stable across SQLAlchemy versions.


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # --- tenants ---------------------------------------------------------
    op.create_table(
        "tenants",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("legal_name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("tenant_tier", sa.Text(), nullable=False, server_default="shared"),
        sa.Column("status", sa.Text(), nullable=False, server_default="provisioning"),
        sa.Column("default_currency_code", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=conv("pk_tenants")),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_tenants_id_is_valid_ulid")),
        sa.CheckConstraint(
            "tenant_tier IN ('shared', 'dedicated')", name=conv("ck_tenants_tenant_tier_is_valid")
        ),
        sa.CheckConstraint(
            "status IN ('provisioning', 'active', 'suspended', 'migrating', 'offboarded')",
            name=conv("ck_tenants_status_is_valid"),
        ),
        sa.CheckConstraint(
            "default_currency_code ~ '^[A-Z]{3}$'",
            name=conv("ck_tenants_default_currency_code_is_iso4217"),
        ),
    )
    op.create_index(
        "ix_tenants_status",
        "tenants",
        ["status"],
        postgresql_where=sa.text("status <> 'active'"),
    )

    # --- users -------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("pin_hash", sa.Text(), nullable=True),
        sa.Column("permission_version", sa.BigInteger(), nullable=False, server_default="1"),
        sa.Column("status", sa.Text(), nullable=False, server_default="invited"),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=conv("pk_users")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_users_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_users_id_is_valid_ulid")),
        sa.CheckConstraint(
            "status IN ('invited', 'active', 'deactivated')", name=conv("ck_users_status_is_valid")
        ),
        sa.CheckConstraint(
            "email IS NOT NULL OR pin_hash IS NOT NULL",
            name=conv("ck_users_has_at_least_one_login_method"),
        ),
    )
    op.create_index("ix_users_tenant_id", "users", ["tenant_id"])
    op.create_index("ix_users_tenant_id_status", "users", ["tenant_id", "status"])
    op.create_index(
        "uq_users_tenant_id_email",
        "users",
        ["tenant_id", "email"],
        unique=True,
        postgresql_where=sa.text("email IS NOT NULL AND deleted_at IS NULL"),
    )

    # --- sessions ------------------------------------------------------------
    op.create_table(
        "sessions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("device_id", sa.Text(), nullable=True),
        sa.Column("refresh_token_hash", sa.Text(), nullable=False),
        sa.Column("issued_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=conv("pk_sessions")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_sessions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=conv("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_sessions_id_is_valid_ulid")),
    )
    op.create_index("ix_sessions_tenant_id", "sessions", ["tenant_id"])
    op.create_index("ix_sessions_user_id", "sessions", ["user_id"])
    op.create_index(
        "ix_sessions_refresh_token_hash", "sessions", ["refresh_token_hash"], unique=True
    )

    # --- updated_at trigger (Technical Architecture v2.0 SS5.1) -------------
    # Authoritative even for raw SQL/bulk writes that bypass the ORM's
    # `onupdate=` (which only fires on ORM-mediated UPDATE statements).
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in ("tenants", "users", "sessions"):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_set_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            EXECUTE FUNCTION set_updated_at();
            """
        )

    # --- Row-Level Security (Data Architecture v2.0 SS4.1) ------------------
    # `tenants` is the scoping root and is not itself RLS-protected.
    # `users`/`sessions` are tenant-owned: RLS here is defense-in-depth
    # underneath the application-layer scoping in the base repository —
    # both must independently agree for a query to return rows. The
    # session variable is set via `SET LOCAL app.tenant_id` at the start
    # of every transaction (transaction-scoped, safe under PgBouncer
    # transaction-mode pooling — Technical Architecture v2.0 Group G).
    for table in ("users", "sessions"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (tenant_id = current_setting('app.tenant_id', true))
            """
        )


def downgrade() -> None:
    for table in ("users", "sessions"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    for table in ("tenants", "users", "sessions"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_set_updated_at ON {table}")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")

    op.drop_table("sessions")
    op.drop_table("users")
    op.drop_table("tenants")
    op.execute("DROP EXTENSION IF EXISTS citext")
