"""tenant platform: subscriptions, settings, feature flags, directory, outbox

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-08

Sprint 4.1 (Tenant Platform). Hand-written, not autogenerated, for the
same reasons as 0001 (partial/NULLS-NOT-DISTINCT unique indexes, CHECK
constraints, RLS policies, trigger functions).

Scope: subscriptions, system_settings, feature_flags,
tenant_directory_entries, outbox_events, plus two additive columns on
existing tables (tenants.metadata, users.is_platform_admin).
Role/Permission/RolePermission/UserRole remain deferred (unchanged from
0001 — still no ``branches`` table for UserRole to reference, and RBAC
still has no consumer).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql.naming import conv

from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ULID_REGEX = r"^[0-9A-HJKMNP-TV-Z]{26}$"


def upgrade() -> None:
    # --- additive columns on existing tables --------------------------------
    op.add_column(
        "tenants",
        sa.Column(
            "metadata", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_platform_admin", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )

    # --- subscriptions -------------------------------------------------------
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("plan_code", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default="trialing"),
        sa.Column("current_period_end", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("trial_end", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("next_billing_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("grace_period_until", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("max_branches", sa.BigInteger(), nullable=False, server_default="1"),
        sa.Column("max_users", sa.BigInteger(), nullable=False, server_default="5"),
        sa.Column("max_monthly_orders", sa.BigInteger(), nullable=False, server_default="1000"),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=conv("pk_subscriptions")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_subscriptions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_subscriptions_id_is_valid_ulid")),
        sa.CheckConstraint(
            "status IN ('trialing', 'active', 'past_due', 'canceled', 'expired')",
            name=conv("ck_subscriptions_status_is_valid"),
        ),
        sa.CheckConstraint(
            "max_branches > 0", name=conv("ck_subscriptions_max_branches_is_positive")
        ),
        sa.CheckConstraint("max_users > 0", name=conv("ck_subscriptions_max_users_is_positive")),
        sa.CheckConstraint(
            "max_monthly_orders > 0", name=conv("ck_subscriptions_max_monthly_orders_is_positive")
        ),
    )
    op.create_index("uq_subscriptions_tenant_id", "subscriptions", ["tenant_id"], unique=True)

    # --- system_settings -------------------------------------------------------
    op.create_table(
        "system_settings",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("branch_id", sa.Text(), nullable=True),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=conv("pk_system_settings")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_system_settings_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_system_settings_id_is_valid_ulid")
        ),
    )
    op.create_index(
        "uq_system_settings_tenant_id_branch_id_key",
        "system_settings",
        ["tenant_id", "branch_id", "key"],
        unique=True,
        postgresql_nulls_not_distinct=True,
    )

    # --- feature_flags -------------------------------------------------------
    op.create_table(
        "feature_flags",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("rollout_percentage", sa.SmallInteger(), nullable=False, server_default="100"),
        sa.Column("start_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("end_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=conv("pk_feature_flags")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_feature_flags_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_feature_flags_id_is_valid_ulid")),
        sa.CheckConstraint(
            "rollout_percentage BETWEEN 0 AND 100",
            name=conv("ck_feature_flags_rollout_percentage_is_valid"),
        ),
    )
    op.create_index("ix_feature_flags_tenant_id", "feature_flags", ["tenant_id"])
    op.create_index(
        "uq_feature_flags_tenant_id_key",
        "feature_flags",
        ["tenant_id", "key"],
        unique=True,
        postgresql_nulls_not_distinct=True,
    )

    # --- tenant_directory_entries ----------------------------------------------
    # Data Architecture v2.0 SS4.4. Not tenant-scoped in the RLS sense —
    # this is routing metadata *about* a tenant, like `tenants` itself.
    op.create_table(
        "tenant_directory_entries",
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("tenant_tier", sa.Text(), nullable=False, server_default="shared"),
        sa.Column("shard_key", sa.Text(), nullable=False, server_default="shard-01"),
        sa.Column("connection_ref", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default="provisioning"),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("tenant_id", name=conv("pk_tenant_directory_entries")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_tenant_directory_entries_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "tenant_tier IN ('shared', 'dedicated')",
            name=conv("ck_tenant_directory_entries_tenant_tier_is_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('provisioning', 'active', 'suspended', 'migrating', 'offboarded')",
            name=conv("ck_tenant_directory_entries_status_is_valid"),
        ),
    )

    # --- outbox_events -----------------------------------------------------
    # Technical Architecture v2.0 Group B / Data Architecture v2.0 SS5.11.
    # No FK to any business table by design (see models.py docstring).
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("aggregate_type", sa.Text(), nullable=False),
        sa.Column("aggregate_id", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("event_version", sa.SmallInteger(), nullable=False, server_default="1"),
        sa.Column("payload", postgresql.JSONB(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("dispatched_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=conv("pk_outbox_events")),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_outbox_events_id_is_valid_ulid")),
    )
    op.create_index("ix_outbox_events_tenant_id", "outbox_events", ["tenant_id"])
    op.create_index(
        "ix_outbox_events_dispatched_at",
        "outbox_events",
        ["dispatched_at"],
        postgresql_where=sa.text("dispatched_at IS NULL"),
    )

    # --- updated_at triggers (reuses the set_updated_at() function from 0001) ---
    for table in ("subscriptions", "system_settings", "feature_flags", "tenant_directory_entries"):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_set_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            EXECUTE FUNCTION set_updated_at();
            """
        )

    # --- Row-Level Security ---------------------------------------------------
    # subscriptions, system_settings, outbox_events: standard tenant-owned
    # policy, identical in shape to 0001's users/sessions policies.
    for table in ("subscriptions", "system_settings", "outbox_events"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (tenant_id = current_setting('app.tenant_id', true))
            """
        )

    # feature_flags: a deliberate variant — a platform-wide flag
    # (tenant_id IS NULL) must remain visible to every tenant, or a
    # global rollout would be invisible to everyone.
    op.execute("ALTER TABLE feature_flags ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON feature_flags
        USING (
            tenant_id IS NULL
            OR tenant_id = current_setting('app.tenant_id', true)
        )
        """
    )

    # tenant_directory_entries: no RLS, matching `tenants` itself — this
    # is platform routing metadata, not a tenant's own data.


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON feature_flags")
    op.execute("ALTER TABLE feature_flags DISABLE ROW LEVEL SECURITY")
    for table in ("subscriptions", "system_settings", "outbox_events"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    for table in ("subscriptions", "system_settings", "feature_flags", "tenant_directory_entries"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_set_updated_at ON {table}")

    op.drop_table("outbox_events")
    op.drop_table("tenant_directory_entries")
    op.drop_table("feature_flags")
    op.drop_table("system_settings")
    op.drop_table("subscriptions")

    op.drop_column("users", "is_platform_admin")
    op.drop_column("tenants", "metadata")
