"""rbac foundation: roles, permissions, role_permissions, user_roles

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-08

Sprint 5, Step 2. Hand-written, not autogenerated, for the same reasons
as 0001/0002 (partial/NULLS-NOT-DISTINCT unique indexes, CHECK
constraints, RLS policies with a deliberately adjusted predicate on
``roles``).

Approved sequencing (RBAC_Foundation_Architecture.md SS15): RBAC is
0003, Restaurant Platform's own schema is 0004 -- reversing the order
the earlier planning document assumed, because Restaurant Platform's
role model cannot be built on ``users.is_platform_admin`` alone.

**Cross-migration dependency, disclosed rather than hidden:**
``user_roles.branch_id`` is created here as a plain, unconstrained
``TEXT`` column (nullable). It cannot carry a real foreign key yet --
the referenced table, ``branches``, does not exist until migration
0004 (Restaurant Platform) creates it. Migration 0004 MUST, as part of
its own upgrade, run:

    ALTER TABLE user_roles
        ADD CONSTRAINT fk_user_roles_branch_id_branches
        FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT;

and, per RBAC_Foundation_Architecture.md SS13.2, a trigger enforcing
that ``user_roles.branch_id``'s own tenant matches ``user_roles.tenant_id``
(cannot be expressed in 0003 for the same reason -- it needs to join
against ``branches``, which doesn't exist yet). Both are called out
again in 0004's own docstring when it is written, so this is not a
dependency that only lives in one place.

Seed data: the 11 "needed now" permissions (RBAC_Foundation_Architecture.md
SS6.2) are seeded directly below -- platform reference data, safe to
seed once. Default Role/RolePermission rows are deliberately NOT seeded
here; they are seeded per-tenant by TenantProvisioningService (a
follow-up commit), matching how tenant-scoped seed data has always been
created in this codebase (see 0002's own docstring precedent). No
UserRole row is seeded by this migration or any follow-up commit --
there is no user to grant one to at migration time, and the approved
decision is explicit: do not invent Tenant Owner assignments.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.sql.naming import conv

from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ULID_REGEX = r"^[0-9A-HJKMNP-TV-Z]{26}$"
_PERMISSION_CODE_REGEX = r"^[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*$"

# RBAC_Foundation_Architecture.md SS6.2's "needed now" catalogue.
# (code, module, description)
_SEED_PERMISSIONS: tuple[tuple[str, str, str], ...] = (
    ("restaurant.read", "restaurant", "View restaurant profile."),
    ("restaurant.manage", "restaurant", "Create and edit restaurant profile."),
    ("branch.read", "restaurant", "View branch details."),
    ("branch.manage", "restaurant", "Create, edit, close, and reopen branches."),
    ("table.read", "restaurant", "View dining areas, tables, and QR codes."),
    ("table.manage", "restaurant", "Create and edit dining areas, tables, and QR codes."),
    ("menu.read", "restaurant", "View menu categories, items, and modifiers."),
    (
        "menu.manage",
        "restaurant",
        "Create and edit menu categories, items, modifiers, pricing, and availability.",
    ),
    ("reservation.read", "restaurant", "View reservations."),
    ("reservation.manage", "restaurant", "Create, confirm, seat, and cancel reservations."),
    ("roles.assign", "identity", "Grant or revoke role assignments."),
)


def upgrade() -> None:
    # --- permissions -----------------------------------------------------------
    # No tenant_id at all -- pure platform reference data, exactly like
    # `currencies` (RBAC_Foundation_Architecture.md SS4.2). `code` is
    # the primary key, a deliberate deviation from the universal ULID
    # convention -- mirrors the `chart_of_accounts.account_code`
    # precedent's own reasoning (not yet built, but the same rationale
    # already established for a small, code-referenced, platform-seeded
    # reference table).
    op.create_table(
        "permissions",
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("module", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code", name=conv("pk_permissions")),
        sa.CheckConstraint(
            f"code ~ '{_PERMISSION_CODE_REGEX}'", name=conv("ck_permissions_code_is_valid")
        ),
    )
    op.create_index("ix_permissions_module", "permissions", ["module"])

    # --- roles -------------------------------------------------------------
    op.create_table(
        "roles",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_scope", sa.Text(), nullable=False, server_default="branch"),
        sa.Column("is_system", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=conv("pk_roles")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_roles_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_roles_id_is_valid_ulid")),
        sa.CheckConstraint(
            "default_scope IN ('tenant', 'branch')", name=conv("ck_roles_default_scope_is_valid")
        ),
    )
    op.create_index("ix_roles_tenant_id", "roles", ["tenant_id"])
    op.create_index(
        "uq_roles_tenant_id_name",
        "roles",
        ["tenant_id", "name"],
        unique=True,
        postgresql_nulls_not_distinct=True,
    )

    # --- role_permissions ----------------------------------------------------
    op.create_table(
        "role_permissions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("role_id", sa.Text(), nullable=False),
        sa.Column("permission_code", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=conv("pk_role_permissions")),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=conv("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["permission_code"],
            ["permissions.code"],
            name=conv("fk_role_permissions_permission_code_permissions"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_role_permissions_id_is_valid_ulid")
        ),
    )
    op.create_index("ix_role_permissions_role_id", "role_permissions", ["role_id"])
    op.create_index(
        "uq_role_permissions_role_id_permission_code",
        "role_permissions",
        ["role_id", "permission_code"],
        unique=True,
    )

    # --- user_roles ----------------------------------------------------------
    # branch_id: plain TEXT, no FK yet -- see module docstring. Soft
    # delete (deleted_at) is the revocation path (Data Architecture v1.0
    # SS3.1: "revocation recorded, not deleted, for audit of who had
    # what access when").
    op.create_table(
        "user_roles",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("role_id", sa.Text(), nullable=False),
        sa.Column("branch_id", sa.Text(), nullable=True),
        sa.Column(
            "granted_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("granted_by_user_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=conv("pk_user_roles")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_user_roles_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=conv("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=conv("fk_user_roles_role_id_roles"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"],
            ["users.id"],
            name=conv("fk_user_roles_granted_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_user_roles_id_is_valid_ulid")),
    )
    op.create_index("ix_user_roles_tenant_id", "user_roles", ["tenant_id"])
    op.create_index("ix_user_roles_user_id", "user_roles", ["user_id"])
    op.create_index("ix_user_roles_role_id", "user_roles", ["role_id"])
    op.create_index("ix_user_roles_branch_id", "user_roles", ["branch_id"])
    op.create_index(
        "uq_user_roles_user_id_role_id_branch_id",
        "user_roles",
        ["user_id", "role_id", "branch_id"],
        unique=True,
        postgresql_nulls_not_distinct=True,
    )

    # --- updated_at triggers (reuses the set_updated_at() function from 0001) ---
    for table in ("permissions", "roles", "user_roles"):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_set_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            EXECUTE FUNCTION set_updated_at();
            """
        )

    # --- Row-Level Security ---------------------------------------------------
    # user_roles: standard tenant-owned policy, identical in shape to
    # every other tenant-scoped table.
    op.execute("ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON user_roles
        USING (tenant_id = current_setting('app.tenant_id', true))
        """
    )

    # roles: a deliberate variant, matching 0002's own feature_flags
    # precedent exactly -- a platform-wide role (tenant_id IS NULL) must
    # remain visible to every tenant, or the naive predicate alone would
    # silently hide it from everyone (RBAC_Foundation_Architecture.md
    # SS14.2). No platform-wide role row exists yet (SS10.1), but the
    # policy is written correctly from the start rather than retrofitted
    # later.
    op.execute("ALTER TABLE roles ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON roles
        USING (
            tenant_id IS NULL
            OR tenant_id = current_setting('app.tenant_id', true)
        )
        """
    )

    # permissions, role_permissions: no RLS -- permissions has no
    # tenant_id column at all (pure platform reference data);
    # role_permissions has no tenant_id column either, access is gated
    # at the API/application layer through role_id's own resolved scope
    # (RBAC_Foundation_Architecture.md SS14.3).

    # --- seed data: the 11 "needed now" permissions ---------------------------
    permissions_table = sa.table(
        "permissions",
        sa.column("code", sa.Text()),
        sa.column("module", sa.Text()),
        sa.column("description", sa.Text()),
    )
    op.bulk_insert(
        permissions_table,
        [
            {"code": code, "module": module, "description": description}
            for code, module, description in _SEED_PERMISSIONS
        ],
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON roles")
    op.execute("ALTER TABLE roles DISABLE ROW LEVEL SECURITY")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON user_roles")
    op.execute("ALTER TABLE user_roles DISABLE ROW LEVEL SECURITY")

    for table in ("permissions", "roles", "user_roles"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_set_updated_at ON {table}")

    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    op.drop_table("roles")
    op.drop_table("permissions")
