"""restaurant platform: restaurants, branches, tables, menu

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-08

Sprint 5, Step 3. Hand-written, not autogenerated, for the same reasons
as 0001/0002/0003 (partial/NULLS-NOT-DISTINCT unique indexes, CHECK
constraints, RLS policies, a cross-migration trigger).

Approved sequencing (RBAC_Foundation_Architecture.md SS15,
RestaurantOS_Restaurant_Platform_Architecture.md SS14): RBAC landed as
0003; this is 0004, purely additive -- 15 new tables
(restaurants, addresses, branches, operating_hours, table_zones,
tables, qr_codes, menu_categories, menu_items, modifier_groups,
modifiers, menu_item_modifier_groups, menu_item_branch_prices,
menu_item_availabilities, reservations), zero modification to any
existing table's columns.

**Closing the cross-migration dependency 0003 opened** (its own
docstring, SS17-33): ``user_roles.branch_id`` was created there as a
plain, unconstrained TEXT column because ``branches`` didn't exist yet.
Now that it does, this migration's upgrade():
  1. Adds the deferred FK: user_roles.branch_id -> branches.id (RESTRICT).
  2. Adds a trigger enforcing that a UserRole grant's branch belongs to
     the *same* tenant as the grant itself (RBAC_Foundation_Architecture.md
     SS13.2's "confused deputy" integrity check -- a CHECK constraint
     cannot reference another table, so a trigger is the correct tool,
     following the same precedent Data Architecture v2.0 Group B
     established for BillAdjustment's approval-threshold rule).
Both are reversed first in downgrade(), before the 15 new tables (and
therefore ``branches``) are dropped.

RLS: every new table except ``qr_codes`` gets the identical
``tenant_id = current_setting('app.tenant_id', true)`` policy already
used throughout 0001-0003 -- no second isolation mechanism
(Restaurant Platform Architecture SS4.2). Branch-level access is a
role-shaped, application-layer filter, not a second RLS policy (SS4.4)
-- no branch-scoped RLS predicate exists on any table here, by design.
``qr_codes`` deliberately has **no** RLS at all: a standard policy
would make the unauthenticated guest token-resolution path (SS3.1) --
looked up by ``token`` alone, before tenant context is known --
structurally impossible, since with no context set every row is
hidden by RLS, including the one being resolved. Caught by this
migration's own test suite, not assumed correct; see the module-level
comment above ``_TENANT_SCOPED_RLS_TABLES`` for the full reasoning.

Seed data: none. Every Restaurant Platform entity is tenant-created,
not platform-seeded (SS14).
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import sqlalchemy as sa
from sqlalchemy.sql.naming import conv

from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ULID_REGEX = r"^[0-9A-HJKMNP-TV-Z]{26}$"

# Every table below except menu_item_modifier_groups (a pure join, no
# independent audit value -- same classification RBAC's own
# RolePermission received in 0003).
_TIMESTAMPED_TABLES = (
    "restaurants",
    "addresses",
    "branches",
    "operating_hours",
    "table_zones",
    "tables",
    "qr_codes",
    "menu_categories",
    "menu_items",
    "modifier_groups",
    "modifiers",
    "menu_item_branch_prices",
    "menu_item_availabilities",
    "reservations",
)

# Tenant-only (no branch dimension): restaurants, addresses,
# menu_categories, menu_items, modifier_groups, modifiers,
# menu_item_modifier_groups -- matches the scoping chain in
# Restaurant Platform Architecture SS4.1 exactly.
_TENANT_SCOPED_RLS_TABLES = (
    "restaurants",
    "addresses",
    "branches",
    "operating_hours",
    "table_zones",
    "tables",
    "menu_categories",
    "menu_items",
    "modifier_groups",
    "modifiers",
    "menu_item_branch_prices",
    "menu_item_availabilities",
    "reservations",
)
# menu_item_modifier_groups: no RLS, matching role_permissions' own
# precedent in 0003 -- a pure join with tenant_id present for
# consistency but access control enforced entirely at the application
# layer via the menu_item_id/modifier_group_id's own resolved scope.
#
# qr_codes: also deliberately no RLS -- caught by this migration's own
# test suite, not assumed correct. Restaurant Platform Architecture
# SS3.1's QRCode entry is explicit that the *resolution* read path (an
# unauthenticated guest scanning a code, looking it up by `token` alone)
# is "a distinct, unauthenticated endpoint... this is an explicit,
# narrow exception to 'every query goes through TenantContext'". A
# standard tenant_id = current_setting('app.tenant_id', true) policy
# makes that path structurally impossible: with no tenant context set
# (which is exactly the resolution path's own precondition --
# tenant_id isn't known yet), current_setting() returns NULL and every
# row is hidden, including the very row the guest is trying to resolve.
# There is no RLS predicate that can distinguish "the trusted resolution
# code path" from "everyone else" -- Postgres RLS only sees column
# values and session settings, not which application code issued the
# query. Tenant scoping for the *management* read path (admin-web) is
# therefore enforced at the application layer only for this one table
# (every repository method still filters `WHERE tenant_id = :tenant_id`
# explicitly), the same single-layer precedent `permissions` already
# established in 0003 for a different reason (pure platform reference
# data there; a structurally-pre-tenant-context read path here).


def _timestamp_columns() -> list[sa.Column[Any]]:
    return [
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
    ]


def upgrade() -> None:
    # --- restaurants -----------------------------------------------------
    op.create_table(
        "restaurants",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("legal_name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        # FK to `currencies.code` intentionally deferred until that
        # reference table exists -- mirrors `tenants.default_currency_code`'s
        # own established precedent (Sprint 3), validated by CHECK for now.
        sa.Column("default_currency_code", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default="active"),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_restaurants")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_restaurants_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_restaurants_id_is_valid_ulid")),
        sa.CheckConstraint(
            "status IN ('active', 'discontinued')", name=conv("ck_restaurants_status_is_valid")
        ),
        sa.CheckConstraint(
            "default_currency_code ~ '^[A-Z]{3}$'",
            name=conv("ck_restaurants_default_currency_code_is_iso4217"),
        ),
    )
    op.create_index("ix_restaurants_tenant_id", "restaurants", ["tenant_id"])

    # --- addresses ---------------------------------------------------------
    op.create_table(
        "addresses",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("line1", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("country_code", sa.Text(), nullable=True),
        sa.Column("postal_code", sa.Text(), nullable=True),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_addresses")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_addresses_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_addresses_id_is_valid_ulid")),
    )
    op.create_index("ix_addresses_tenant_id", "addresses", ["tenant_id"])

    # --- branches ------------------------------------------------------------
    op.create_table(
        "branches",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("restaurant_id", sa.Text(), nullable=False),
        sa.Column("address_id", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default="active"),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_branches")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_branches_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=conv("fk_branches_restaurant_id_restaurants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["addresses.id"],
            name=conv("fk_branches_address_id_addresses"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_branches_id_is_valid_ulid")),
        sa.CheckConstraint(
            "status IN ('opened', 'active', 'temporarily_closed', 'permanently_closed')",
            name=conv("ck_branches_status_is_valid"),
        ),
    )
    op.create_index("ix_branches_tenant_id", "branches", ["tenant_id"])
    op.create_index("ix_branches_restaurant_id", "branches", ["restaurant_id"])
    op.create_index(
        "uq_branches_restaurant_id_name", "branches", ["restaurant_id", "name"], unique=True
    )

    # --- operating_hours -----------------------------------------------------
    op.create_table(
        "operating_hours",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("branch_id", sa.Text(), nullable=False),
        sa.Column("day_of_week", sa.SmallInteger(), nullable=False),
        sa.Column("opens_at", sa.Time(), nullable=True),
        sa.Column("closes_at", sa.Time(), nullable=True),
        sa.Column("is_closed", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_operating_hours")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_operating_hours_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=conv("fk_operating_hours_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_operating_hours_id_is_valid_ulid")
        ),
        sa.CheckConstraint(
            "day_of_week BETWEEN 0 AND 6", name=conv("ck_operating_hours_day_of_week_is_valid")
        ),
        sa.CheckConstraint(
            "opens_at < closes_at OR is_closed",
            name=conv("ck_operating_hours_opens_before_closes"),
        ),
    )
    op.create_index("ix_operating_hours_tenant_id", "operating_hours", ["tenant_id"])
    op.create_index("ix_operating_hours_branch_id", "operating_hours", ["branch_id"])

    # --- table_zones ---------------------------------------------------------
    op.create_table(
        "table_zones",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("branch_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False, server_default="0"),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_table_zones")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_table_zones_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=conv("fk_table_zones_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_table_zones_id_is_valid_ulid")),
    )
    op.create_index("ix_table_zones_tenant_id", "table_zones", ["tenant_id"])
    op.create_index("ix_table_zones_branch_id", "table_zones", ["branch_id"])
    op.create_index(
        "uq_table_zones_branch_id_name", "table_zones", ["branch_id", "name"], unique=True
    )

    # --- tables ----------------------------------------------------------
    op.create_table(
        "tables",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("branch_id", sa.Text(), nullable=False),
        sa.Column("table_zone_id", sa.Text(), nullable=False),
        sa.Column("table_number", sa.Text(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default="available"),
        sa.Column("sync_version", sa.BigInteger(), nullable=False, server_default="0"),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_tables")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_tables_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=conv("fk_tables_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["table_zone_id"],
            ["table_zones.id"],
            name=conv("fk_tables_table_zone_id_table_zones"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_tables_id_is_valid_ulid")),
        sa.CheckConstraint("capacity > 0", name=conv("ck_tables_capacity_is_positive")),
        sa.CheckConstraint(
            "status IN ('available', 'occupied', 'reserved', 'cleaning')",
            name=conv("ck_tables_status_is_valid"),
        ),
    )
    op.create_index("ix_tables_tenant_id", "tables", ["tenant_id"])
    op.create_index("ix_tables_branch_id_status", "tables", ["branch_id", "status"])
    op.create_index("ix_tables_table_zone_id", "tables", ["table_zone_id"])
    op.create_index(
        "uq_tables_branch_id_table_number", "tables", ["branch_id", "table_number"], unique=True
    )

    # --- qr_codes ------------------------------------------------------------
    op.create_table(
        "qr_codes",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("branch_id", sa.Text(), nullable=False),
        sa.Column("table_id", sa.Text(), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default="active"),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_qr_codes")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_qr_codes_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=conv("fk_qr_codes_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["tables.id"],
            name=conv("fk_qr_codes_table_id_tables"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_qr_codes_id_is_valid_ulid")),
        sa.CheckConstraint(
            "status IN ('active', 'revoked')", name=conv("ck_qr_codes_status_is_valid")
        ),
    )
    op.create_index("ix_qr_codes_tenant_id", "qr_codes", ["tenant_id"])
    op.create_index("ix_qr_codes_table_id", "qr_codes", ["table_id"])
    # Global, not tenant-scoped -- resolved from an unauthenticated guest
    # request before tenant context is known (SS3.1's QRCode note).
    op.create_index("uq_qr_codes_token", "qr_codes", ["token"], unique=True)

    # --- menu_categories -------------------------------------------------
    op.create_table(
        "menu_categories",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("restaurant_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False, server_default="0"),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_menu_categories")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_menu_categories_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=conv("fk_menu_categories_restaurant_id_restaurants"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_menu_categories_id_is_valid_ulid")
        ),
    )
    op.create_index("ix_menu_categories_tenant_id", "menu_categories", ["tenant_id"])
    op.create_index("ix_menu_categories_restaurant_id", "menu_categories", ["restaurant_id"])
    op.create_index(
        "uq_menu_categories_restaurant_id_name",
        "menu_categories",
        ["restaurant_id", "name"],
        unique=True,
    )

    # --- menu_items --------------------------------------------------------
    op.create_table(
        "menu_items",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("menu_category_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("price_amount", sa.Numeric(19, 4), nullable=False),
        sa.Column("currency_code", sa.Text(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("display_order", sa.Integer(), nullable=False, server_default="0"),
        # Inventory Platform's future FK target -- reserved, unpopulated,
        # no FK yet (Recipe doesn't exist -- SS3.1's own disclosed scope).
        sa.Column("recipe_id", sa.Text(), nullable=True),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_menu_items")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_menu_items_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["menu_category_id"],
            ["menu_categories.id"],
            name=conv("fk_menu_items_menu_category_id_menu_categories"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_menu_items_id_is_valid_ulid")),
        sa.CheckConstraint(
            "price_amount >= 0", name=conv("ck_menu_items_price_amount_is_non_negative")
        ),
        sa.CheckConstraint(
            "currency_code ~ '^[A-Z]{3}$'", name=conv("ck_menu_items_currency_code_is_iso4217")
        ),
    )
    op.create_index("ix_menu_items_tenant_id", "menu_items", ["tenant_id"])
    op.create_index("ix_menu_items_menu_category_id", "menu_items", ["menu_category_id"])

    # --- modifier_groups -----------------------------------------------------
    op.create_table(
        "modifier_groups",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("selection_type", sa.Text(), nullable=False),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_modifier_groups")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_modifier_groups_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_modifier_groups_id_is_valid_ulid")
        ),
        sa.CheckConstraint(
            "selection_type IN ('single', 'multiple')",
            name=conv("ck_modifier_groups_selection_type_is_valid"),
        ),
    )
    op.create_index("ix_modifier_groups_tenant_id", "modifier_groups", ["tenant_id"])

    # --- modifiers -----------------------------------------------------------
    op.create_table(
        "modifiers",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("modifier_group_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("price_delta", sa.Numeric(19, 4), nullable=False, server_default="0"),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_modifiers")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_modifiers_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["modifier_group_id"],
            ["modifier_groups.id"],
            name=conv("fk_modifiers_modifier_group_id_modifier_groups"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_modifiers_id_is_valid_ulid")),
    )
    op.create_index("ix_modifiers_tenant_id", "modifiers", ["tenant_id"])
    op.create_index("ix_modifiers_modifier_group_id", "modifiers", ["modifier_group_id"])

    # --- menu_item_modifier_groups ---------------------------------------
    # Pure join, no independent audit value (Data Architecture v2.0 Group F)
    # -- same classification role_permissions received in 0003.
    op.create_table(
        "menu_item_modifier_groups",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("menu_item_id", sa.Text(), nullable=False),
        sa.Column("modifier_group_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=conv("pk_menu_item_modifier_groups")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_menu_item_modifier_groups_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["menu_item_id"],
            ["menu_items.id"],
            name=conv("fk_menu_item_modifier_groups_menu_item_id_menu_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["modifier_group_id"],
            ["modifier_groups.id"],
            name=conv("fk_menu_item_modifier_groups_modifier_group_id_modifier_groups"),
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_menu_item_modifier_groups_id_is_valid_ulid")
        ),
    )
    op.create_index(
        "ix_menu_item_modifier_groups_menu_item_id", "menu_item_modifier_groups", ["menu_item_id"]
    )
    op.create_index(
        "uq_menu_item_modifier_groups_menu_item_id_modifier_group_id",
        "menu_item_modifier_groups",
        ["menu_item_id", "modifier_group_id"],
        unique=True,
    )

    # --- menu_item_branch_prices -------------------------------------------
    op.create_table(
        "menu_item_branch_prices",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("branch_id", sa.Text(), nullable=False),
        sa.Column("menu_item_id", sa.Text(), nullable=False),
        sa.Column("price_amount", sa.Numeric(19, 4), nullable=False),
        sa.Column("effective_from", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("effective_to", sa.TIMESTAMP(timezone=True), nullable=True),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_menu_item_branch_prices")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_menu_item_branch_prices_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=conv("fk_menu_item_branch_prices_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["menu_item_id"],
            ["menu_items.id"],
            name=conv("fk_menu_item_branch_prices_menu_item_id_menu_items"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_menu_item_branch_prices_id_is_valid_ulid")
        ),
        sa.CheckConstraint(
            "price_amount >= 0",
            name=conv("ck_menu_item_branch_prices_price_amount_is_non_negative"),
        ),
        sa.CheckConstraint(
            "effective_from < effective_to OR effective_to IS NULL",
            name=conv("ck_menu_item_branch_prices_effective_window_is_valid"),
        ),
    )
    op.create_index(
        "ix_menu_item_branch_prices_menu_item_id_branch_id",
        "menu_item_branch_prices",
        ["menu_item_id", "branch_id"],
    )

    # --- menu_item_availabilities --------------------------------------
    op.create_table(
        "menu_item_availabilities",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("branch_id", sa.Text(), nullable=False),
        sa.Column("menu_item_id", sa.Text(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("effective_from", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("effective_to", sa.TIMESTAMP(timezone=True), nullable=True),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_menu_item_availabilities")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_menu_item_availabilities_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=conv("fk_menu_item_availabilities_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["menu_item_id"],
            ["menu_items.id"],
            name=conv("fk_menu_item_availabilities_menu_item_id_menu_items"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_menu_item_availabilities_id_is_valid_ulid")
        ),
        sa.CheckConstraint(
            "effective_from < effective_to OR effective_to IS NULL",
            name=conv("ck_menu_item_availabilities_effective_window_is_valid"),
        ),
    )
    op.create_index(
        "ix_menu_item_availabilities_menu_item_id_branch_id",
        "menu_item_availabilities",
        ["menu_item_id", "branch_id"],
    )

    # --- reservations --------------------------------------------------------
    op.create_table(
        "reservations",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("branch_id", sa.Text(), nullable=False),
        sa.Column("table_id", sa.Text(), nullable=True),
        # Customer doesn't exist yet (future CRM Platform) -- reserved,
        # unpopulated, no FK, matching menu_items.recipe_id's own pattern.
        sa.Column("customer_id", sa.Text(), nullable=True),
        sa.Column("party_size", sa.Integer(), nullable=False),
        sa.Column("requested_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default="requested"),
        sa.Column("sync_version", sa.BigInteger(), nullable=False, server_default="0"),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_reservations")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_reservations_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=conv("fk_reservations_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["tables.id"],
            name=conv("fk_reservations_table_id_tables"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_reservations_id_is_valid_ulid")),
        sa.CheckConstraint("party_size > 0", name=conv("ck_reservations_party_size_is_positive")),
        sa.CheckConstraint(
            "status IN ('requested', 'confirmed', 'seated', 'completed', 'no_show', 'canceled')",
            name=conv("ck_reservations_status_is_valid"),
        ),
    )
    op.create_index("ix_reservations_tenant_id", "reservations", ["tenant_id"])
    op.create_index("ix_reservations_branch_id", "reservations", ["branch_id"])
    op.create_index("ix_reservations_table_id", "reservations", ["table_id"])

    # --- updated_at triggers (reuses set_updated_at() from 0001) -------------
    for table in _TIMESTAMPED_TABLES:
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_set_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            EXECUTE FUNCTION set_updated_at();
            """
        )

    # --- Row-Level Security ---------------------------------------------------
    for table in _TENANT_SCOPED_RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (tenant_id = current_setting('app.tenant_id', true))
            """
        )
    # menu_item_modifier_groups: RLS enabled too (it does have tenant_id,
    # unlike role_permissions which has none) -- consistent with every
    # other tenant-scoped table in this migration.
    op.execute("ALTER TABLE menu_item_modifier_groups ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON menu_item_modifier_groups
        USING (tenant_id = current_setting('app.tenant_id', true))
        """
    )

    # --- close the 0003 cross-migration dependency ---------------------------
    op.execute(
        """
        ALTER TABLE user_roles
            ADD CONSTRAINT fk_user_roles_branch_id_branches
            FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION check_user_role_branch_tenant_consistency()
        RETURNS TRIGGER AS $$
        DECLARE
            branch_tenant_id TEXT;
        BEGIN
            IF NEW.branch_id IS NOT NULL THEN
                SELECT tenant_id INTO branch_tenant_id FROM branches WHERE id = NEW.branch_id;
                IF branch_tenant_id IS DISTINCT FROM NEW.tenant_id THEN
                    RAISE EXCEPTION
                        'user_roles.branch_id % belongs to a different tenant than user_roles.tenant_id %',
                        NEW.branch_id, NEW.tenant_id;
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_user_roles_branch_tenant_consistency
        BEFORE INSERT OR UPDATE ON user_roles
        FOR EACH ROW
        EXECUTE FUNCTION check_user_role_branch_tenant_consistency();
        """
    )


def downgrade() -> None:
    # --- reverse the 0003 cross-migration dependency first --------------------
    op.execute("DROP TRIGGER IF EXISTS trg_user_roles_branch_tenant_consistency ON user_roles")
    op.execute("DROP FUNCTION IF EXISTS check_user_role_branch_tenant_consistency()")
    op.execute("ALTER TABLE user_roles DROP CONSTRAINT IF EXISTS fk_user_roles_branch_id_branches")

    op.execute("DROP POLICY IF EXISTS tenant_isolation ON menu_item_modifier_groups")
    op.execute("ALTER TABLE menu_item_modifier_groups DISABLE ROW LEVEL SECURITY")
    for table in _TENANT_SCOPED_RLS_TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    for table in _TIMESTAMPED_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_set_updated_at ON {table}")

    # Drop in FK-dependency order: children before parents.
    op.drop_table("reservations")
    op.drop_table("menu_item_availabilities")
    op.drop_table("menu_item_branch_prices")
    op.drop_table("menu_item_modifier_groups")
    op.drop_table("modifiers")
    op.drop_table("modifier_groups")
    op.drop_table("menu_items")
    op.drop_table("menu_categories")
    op.drop_table("qr_codes")
    op.drop_table("tables")
    op.drop_table("table_zones")
    op.drop_table("operating_hours")
    op.drop_table("branches")
    op.drop_table("addresses")
    op.drop_table("restaurants")
