"""shared infrastructure: idempotency keys, effective-window exclusion

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-08

Sprint 5, Step 4.0. Hand-written, not autogenerated -- same reasons as
0001-0004 (a Postgres extension, GiST exclusion constraints, RLS).

Two, deliberately unrelated-looking but both-approved-together pieces
of shared infrastructure, per the Step 4 "Decision Lock" the user
reviewed and approved before this migration was written:

1. **Idempotency** (Technical Architecture v2.0 Group B/E, `platform/
   idempotency/` -- a pre-existing, disclosed gap neither Sprint 4.1
   nor Sprint 5 Steps 1-3 closed, closed here because Step 4's own
   mutating endpoints need it same as Tenant Administration's always
   did). `idempotency_keys`: one row per `(tenant_id, idempotency_key)`,
   inserted *before* the guarded use case runs (the concurrency-safety
   mechanism -- a concurrent duplicate request hits the `UNIQUE`
   constraint immediately rather than racing the use case body), then
   updated with the computed response once the use case completes. A
   repeat call with the same key and the same request body's SHA-256
   fingerprint replays the stored response without re-executing
   anything; the same key with a *different* fingerprint is rejected as
   a client error at the application layer (`platform/idempotency/`) --
   this migration only provides the storage, not that logic.

2. **Effective-window overlap prevention** for
   `menu_item_branch_prices`/`menu_item_availabilities` (Restaurant
   Platform Architecture SS3.1's override-window pattern, closed here
   per the Step 4 Decision Lock's explicit instruction: "reject-on-
   overlap", enforced *transactionally* so concurrent requests cannot
   both insert overlapping windows). A `CHECK` constraint cannot express
   "no other row for this (menu_item_id, branch_id) has an overlapping
   [effective_from, effective_to) range" -- that requires comparing
   against *other rows*, which is exactly what a GiST `EXCLUDE`
   constraint is for (the same category of tool 0004's cross-table
   trigger was needed for a different reason: a `CHECK` constraint
   cannot reference another table *or* other rows of the same table).
   `btree_gist` (`CREATE EXTENSION IF NOT EXISTS`, following 0001's own
   `citext` precedent for enabling a Postgres extension a real
   constraint need requires) lets the exclusion constraint combine
   plain equality columns (`menu_item_id`, `branch_id`) with a range
   `&&` (overlaps) operator on `tstzrange(effective_from, effective_to,
   '[)')` -- `tstzrange` treats a NULL `effective_to` as unbounded
   automatically, so an existing open-ended window correctly conflicts
   with any later window that would start before it "ends". The
   application layer still does a friendly pre-check (Step 4's own use
   cases) to return a clean `EFFECTIVE_WINDOW_OVERLAP` error instead of
   surfacing a raw constraint-violation message, but this constraint is
   the actual, race-free guarantee -- matching this codebase's
   established "proactive check + DB constraint as the real backstop"
   pattern (`UserRoleRepository.exists()`'s own precedent).

Explicitly NOT in this migration (per the Decision Lock's own scope
boundary -- "do not add unrelated schema"): the QR-code rate-limiting
counter table (Decision 6) is separate shared infrastructure with a
different consumer (the unauthenticated QR resolution endpoint, Step
4.7) and lands in its own migration when that step is reached, not
bundled in here. `sync_version` remains untouched -- Decision 7 of the
same Decision Lock explicitly keeps it inert this sprint (Restaurant
Platform Architecture SS10.3: "No conflict resolution code is written
this sprint"), so no migration change is needed or made for it here.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql.naming import conv

from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ULID_REGEX = r"^[0-9A-HJKMNP-TV-Z]{26}$"


def upgrade() -> None:
    # --- idempotency_keys --------------------------------------------------
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("request_fingerprint", sa.Text(), nullable=False),
        # NULL until the guarded use case completes -- the placeholder
        # row itself (inserted before execution) is what makes a
        # concurrent duplicate request fail fast on the UNIQUE
        # constraint below, rather than racing the use case body.
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=conv("pk_idempotency_keys")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_idempotency_keys_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_idempotency_keys_id_is_valid_ulid")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "idempotency_key",
            name=conv("uq_idempotency_keys_tenant_id_idempotency_key"),
        ),
    )
    op.create_index("ix_idempotency_keys_tenant_id", "idempotency_keys", ["tenant_id"])
    # Supports the (not-yet-built, out of scope here) periodic cleanup
    # job that deletes expired rows -- an index every future consumer
    # of "delete WHERE expires_at < now()" needs, not a speculative one.
    op.create_index("ix_idempotency_keys_expires_at", "idempotency_keys", ["expires_at"])

    op.execute("ALTER TABLE idempotency_keys ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON idempotency_keys
        USING (tenant_id = current_setting('app.tenant_id', true))
        """
    )

    # --- effective-window overlap prevention --------------------------------
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute(
        """
        ALTER TABLE menu_item_branch_prices
            ADD CONSTRAINT excl_menu_item_branch_prices_no_overlap
            EXCLUDE USING gist (
                menu_item_id WITH =,
                branch_id WITH =,
                tstzrange(effective_from, effective_to, '[)') WITH &&
            )
        """
    )
    op.execute(
        """
        ALTER TABLE menu_item_availabilities
            ADD CONSTRAINT excl_menu_item_availabilities_no_overlap
            EXCLUDE USING gist (
                menu_item_id WITH =,
                branch_id WITH =,
                tstzrange(effective_from, effective_to, '[)') WITH &&
            )
        """
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE menu_item_availabilities "
        "DROP CONSTRAINT IF EXISTS excl_menu_item_availabilities_no_overlap"
    )
    op.execute(
        "ALTER TABLE menu_item_branch_prices "
        "DROP CONSTRAINT IF EXISTS excl_menu_item_branch_prices_no_overlap"
    )
    op.execute("DROP EXTENSION IF EXISTS btree_gist")

    op.execute("DROP POLICY IF EXISTS tenant_isolation ON idempotency_keys")
    op.execute("ALTER TABLE idempotency_keys DISABLE ROW LEVEL SECURITY")
    op.drop_table("idempotency_keys")
