"""qr resolution rate limiting

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-09

Sprint 5, Step 4.7. Hand-written, not autogenerated -- same reasons as
0001-0005 (no RLS on this table, by design; see below).

The QR-code rate-limiting counter table promised by migration 0005's
own docstring: "the QR-code rate-limiting counter table (Decision 6)
is separate shared infrastructure with a different consumer (the
unauthenticated QR resolution endpoint, Step 4.7) and lands in its own
migration when that step is reached, not bundled in [0005]." That step
is this one.

``qr_resolution_rate_limits`` backs ADR 0001's rate-limiting
requirements for ``GET /api/v1/qr/{token}`` -- per source IP and per
token, with a stricter limit for failed resolutions than successful
ones. Design: a fixed-window counter, one row per
``(bucket_type, bucket_key, window_start)``, incremented via a single
atomic ``INSERT ... ON CONFLICT DO UPDATE ... RETURNING`` statement
(the same category of tool ``idempotency_keys``' own
insert-a-placeholder-row pattern uses for concurrency safety, applied
here to a counter instead of a claim) -- concurrent requests against
the same bucket in the same window serialize on that row's own lock,
so the count a request sees via ``RETURNING`` is always the true
post-increment value, and "N concurrent requests, only limit-many
succeed" holds under real concurrency, not just sequential testing.

**Deliberately no RLS on this table, for the same structural reason
ADR 0001 gives for ``qr_codes`` itself:** the whole point of this
table is bucketing an unauthenticated caller's request *before* any
tenant context exists -- an IP-address bucket has no tenant at all,
and a token bucket keyed on a guessed/invalid token has no tenant
either (that is exactly the case being rate-limited). There is no
``tenant_id`` column on this table for a policy to key on in the first
place; it is, structurally, the same category of table
``permissions``/``qr_codes`` already established a no-RLS precedent
for, not a new, second isolation mechanism (architecture SS4.2).

Explicitly NOT introduced here, per the user's own Step 4.7 scope:
Redis, a background cleanup job for expired windows (the
``ix_qr_resolution_rate_limits_window_start`` index below exists to
support that *future* job, mirroring ``idempotency_keys``'
``ix_idempotency_keys_expires_at``'s own identical precedent -- an
index every future consumer of "delete WHERE window_start < now() -
retention" needs, not a speculative one), and any change to
``qr_codes``' own RLS-less design (unchanged from migration 0004/ADR
0001).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.sql.naming import conv

from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ULID_REGEX = r"^[0-9A-HJKMNP-TV-Z]{26}$"


def upgrade() -> None:
    op.create_table(
        "qr_resolution_rate_limits",
        sa.Column("id", sa.Text(), nullable=False),
        # 'ip' or 'token' -- which dimension this counter row buckets on.
        sa.Column("bucket_type", sa.Text(), nullable=False),
        # The source IP string or the raw token value being bucketed.
        # Deliberately not a foreign key to qr_codes.token: an 'ip'
        # bucket has nothing to reference, and a 'token' bucket must
        # still count attempts against a token that turns out not to
        # exist at all (that is the case being rate-limited).
        sa.Column("bucket_key", sa.Text(), nullable=False),
        # Fixed-window boundary this row's counts belong to (the window
        # size is an application-layer constant, not enforced here).
        sa.Column("window_start", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("failed_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=conv("pk_qr_resolution_rate_limits")),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_qr_resolution_rate_limits_id_is_valid_ulid")
        ),
        sa.CheckConstraint(
            "bucket_type IN ('ip', 'token')",
            name=conv("ck_qr_resolution_rate_limits_bucket_type_is_valid"),
        ),
        sa.CheckConstraint(
            "total_count >= 0",
            name=conv("ck_qr_resolution_rate_limits_total_count_is_non_negative"),
        ),
        sa.CheckConstraint(
            "failed_count >= 0",
            name=conv("ck_qr_resolution_rate_limits_failed_count_is_non_negative"),
        ),
        sa.CheckConstraint(
            "failed_count <= total_count",
            name=conv("ck_qr_resolution_rate_limits_failed_not_more_than_total"),
        ),
        # The atomic-upsert conflict target (INSERT ... ON CONFLICT
        # (bucket_type, bucket_key, window_start) DO UPDATE ...) -- this
        # unique index *is* the concurrency-safety mechanism, not merely
        # a lookup optimization.
        sa.UniqueConstraint(
            "bucket_type",
            "bucket_key",
            "window_start",
            name=conv("uq_qr_resolution_rate_limits_bucket_window"),
        ),
    )
    op.create_index(
        "ix_qr_resolution_rate_limits_window_start", "qr_resolution_rate_limits", ["window_start"]
    )


def downgrade() -> None:
    op.drop_table("qr_resolution_rate_limits")
