"""day-to-day operations: orders, kitchen, billing, payments, ledger, inventory, purchasing

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-10

Sprint 7, Step 2 (RestaurantOS_DayToDay_Operations_Architecture.md SS9,
SS13). Hand-written, not autogenerated, for the same reasons as every
prior migration in this codebase (CHECK constraints, RLS policies, a
combined trigger function, seed data).

Approved sequencing: the Restaurant Platform backend (0001-0006) is
frozen and untouched by this migration -- purely additive. 26 new
tables (tabs, orders, order_items, kitchen_tickets, kitchen_items,
taxes, discounts, promo_codes, bills, bill_adjustments,
order_tax_lines, payments, refunds, cash_drawers, chart_of_accounts,
ledger_entries, recipes, recipe_ingredients, inventory_categories,
inventory_items, stock_movements, stock_adjustments, suppliers,
purchase_orders, purchase_order_items, goods_receipts) plus one
additive column on the existing, frozen ``branches`` table
(``allow_negative_stock``) plus 12 new RBAC permission rows appended to
the existing ``permissions`` table. Zero modification to any existing
table's columns or any existing row.

Scope decision recorded here: the user approved "Day-to-Day
Operations, online-only v1" -- Data Architecture v1.0 SS8's offline-sync
machinery (client/server operation log, HLC, Conflict Resolution
Registry, Redis Streams relay) is explicitly deferred, matching
Architecture doc SS8's option 1. No table here carries a
``sync_version`` column as a result -- ``SyncVersionedMixin`` is
reserved for the "Exclusive shared state" conflict-registry entries
Technical Architecture v2.0 Group A actually classifies (``Table.status``,
``Reservation.table_id``), and this migration adds none of those.

Financial-ledger integrity (Data Architecture v2.0 Group I): every
INSERT into ``ledger_entries`` is expected to arrive as matched
debit+credit rows in the same transaction as the fact it records --
enforced by application-layer discipline in the use cases that write
it (Step 3+), not a database constraint, since a CHECK/trigger cannot
see "the other half" of a multi-row balanced entry at INSERT time
without a more invasive design this step doesn't need yet.

Negative-inventory enforcement (Data Architecture v2.0 Group D): one
combined BEFORE INSERT trigger function on ``stock_movements`` --
computes the resulting balance from ``inventory_items.quantity_on_hand``,
rejects the insert unless ``branches.allow_negative_stock`` or the
specific row's ``inventory_items.allow_negative_stock_override``
permits it, and (only if not rejected) updates
``inventory_items.quantity_on_hand`` in the same statement. A CHECK
constraint cannot aggregate sibling rows, so this has to be a trigger,
following the same precedent 0004 established for
``check_user_role_branch_tenant_consistency()``.

RLS: every new table except ``chart_of_accounts`` gets the identical
``tenant_id = current_setting('app.tenant_id', true)`` policy already
used throughout 0001-0004 -- no second isolation mechanism.
``chart_of_accounts`` deliberately has **no** tenant_id column and
**no** RLS at all -- pure platform-seeded reference data, the same
"pure platform reference data, exactly like ``currencies``" precedent
0003 already established for ``permissions`` (0003's own docstring for
``permissions`` explicitly anticipated this: "mirrors the
``chart_of_accounts.account_code`` precedent's own reasoning (not yet
built, but the same rationale already established...)" -- this
migration is where that precedent becomes real).

Seed data: 8 platform-seeded ``chart_of_accounts`` rows (Cash, Card
Clearing, Sales Revenue, Sales Tax Payable, COGS, Inventory Asset,
Accounts Payable, Tips Payable) and 12 new ``permissions`` rows
(``order.read``/``order.manage``, ``kitchen.read``/``kitchen.manage``,
``billing.read``/``billing.manage``/``billing.refund``,
``inventory.read``/``inventory.manage``,
``purchasing.read``/``purchasing.manage``, ``ledger.read``) appended to
the existing tables via the same ``op.bulk_insert`` pattern 0003 used.
No role is granted any of these permissions here -- that is a future
step's decision, matching how 0003 seeded permissions without granting
them to any role either.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import sqlalchemy as sa
from sqlalchemy.sql.naming import conv

from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ULID_REGEX = r"^[0-9A-HJKMNP-TV-Z]{26}$"

# Tables carrying created_at + updated_at (soft-deletable or not) --
# get the standard set_updated_at() trigger from 0001.
_TIMESTAMPED_TABLES = (
    "tabs",
    "orders",
    "order_items",
    "kitchen_tickets",
    "kitchen_items",
    "taxes",
    "discounts",
    "promo_codes",
    "bills",
    "payments",
    "refunds",
    "cash_drawers",
    "chart_of_accounts",
    "recipes",
    "recipe_ingredients",
    "inventory_categories",
    "inventory_items",
    "stock_adjustments",
    "suppliers",
    "purchase_orders",
    "purchase_order_items",
    "goods_receipts",
)
# bill_adjustments, order_tax_lines, ledger_entries, stock_movements:
# created_at only -- write-once, append-only facts, no updated_at
# column exists to trigger on (Data Architecture v2.0 Group I/D and
# Architecture doc SS3.3/SS3.6's own "written once, never edited").

# Every new table except chart_of_accounts (global reference data, see
# module docstring).
_TENANT_SCOPED_RLS_TABLES = (
    "tabs",
    "orders",
    "order_items",
    "kitchen_tickets",
    "kitchen_items",
    "taxes",
    "discounts",
    "promo_codes",
    "bills",
    "bill_adjustments",
    "order_tax_lines",
    "payments",
    "refunds",
    "cash_drawers",
    "ledger_entries",
    "recipes",
    "recipe_ingredients",
    "inventory_categories",
    "inventory_items",
    "stock_movements",
    "stock_adjustments",
    "suppliers",
    "purchase_orders",
    "purchase_order_items",
    "goods_receipts",
)

# (code, module, description)
_SEED_PERMISSIONS: tuple[tuple[str, str, str], ...] = (
    ("order.read", "operations", "View orders and their line items."),
    ("order.manage", "operations", "Take, fire, close, and void orders."),
    ("kitchen.read", "operations", "View the kitchen ticket/item feed."),
    ("kitchen.manage", "operations", "Update kitchen ticket and item status."),
    ("billing.read", "operations", "View bills and payments."),
    ("billing.manage", "operations", "Generate bills, apply adjustments, and record payments."),
    ("billing.refund", "operations", "Approve and process refunds."),
    ("inventory.read", "operations", "View inventory items and stock movements."),
    ("inventory.manage", "operations", "Adjust stock and log waste."),
    ("purchasing.read", "operations", "View suppliers and purchase orders."),
    ("purchasing.manage", "operations", "Create and manage suppliers and purchase orders."),
    ("ledger.read", "operations", "View the financial ledger."),
)

_SEED_CHART_OF_ACCOUNTS: tuple[tuple[str, str, str], ...] = (
    ("CASH", "Cash", "asset"),
    ("CARD_CLEARING", "Card Clearing", "asset"),
    ("SALES_REVENUE", "Sales Revenue", "revenue"),
    ("SALES_TAX_PAYABLE", "Sales Tax Payable", "liability"),
    ("COGS", "Cost of Goods Sold", "expense"),
    ("INVENTORY_ASSET", "Inventory Asset", "asset"),
    ("ACCOUNTS_PAYABLE", "Accounts Payable", "liability"),
    ("TIPS_PAYABLE", "Tips Payable", "liability"),
)


def _ts_soft_delete() -> list[sa.Column[Any]]:
    """created_at + updated_at + deleted_at, the full soft-deletable set."""
    return [
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
    ]


def _ts_immutable() -> list[sa.Column[Any]]:
    """created_at + updated_at, no deleted_at -- Immutable-lifecycle entities."""
    return [
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    ]


def _ts_append_only() -> list[sa.Column[Any]]:
    """created_at only -- write-once, append-only ledger/event rows."""
    return [
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    ]


def upgrade() -> None:
    # --- branches.allow_negative_stock (additive column on a frozen table) --
    op.add_column(
        "branches",
        sa.Column(
            "allow_negative_stock", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )

    # --- tabs --------------------------------------------------------------
    op.create_table(
        "tabs",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("branch_id", sa.Text(), nullable=False),
        sa.Column("table_id", sa.Text(), nullable=True),
        sa.Column("customer_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False, server_default="open"),
        sa.Column(
            "opened_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        *_ts_immutable(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_tabs")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_tabs_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=conv("fk_tabs_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"], ["tables.id"], name=conv("fk_tabs_table_id_tables"), ondelete="RESTRICT"
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_tabs_id_is_valid_ulid")),
        sa.CheckConstraint("status IN ('open', 'closed')", name=conv("ck_tabs_status_is_valid")),
    )
    op.create_index("ix_tabs_tenant_id", "tabs", ["tenant_id"])
    op.create_index("ix_tabs_branch_id", "tabs", ["branch_id"])

    # --- orders --------------------------------------------------------------
    op.create_table(
        "orders",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("branch_id", sa.Text(), nullable=False),
        sa.Column("table_id", sa.Text(), nullable=True),
        sa.Column("tab_id", sa.Text(), nullable=True),
        # Customer doesn't exist yet (future CRM Platform) -- reserved,
        # unpopulated, no FK, matching reservations.customer_id's own pattern.
        sa.Column("customer_id", sa.Text(), nullable=True),
        sa.Column("order_source", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default="open"),
        sa.Column("subtotal_amount", sa.Numeric(19, 4), nullable=False, server_default="0"),
        sa.Column("tax_amount", sa.Numeric(19, 4), nullable=False, server_default="0"),
        sa.Column(
            "total_amount",
            sa.Numeric(19, 4),
            sa.Computed("subtotal_amount + tax_amount", persisted=True),
            nullable=False,
        ),
        sa.Column("currency_code", sa.Text(), nullable=False),
        sa.Column(
            "opened_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("origin_device_id", sa.Text(), nullable=True),
        *_ts_immutable(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_orders")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_orders_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=conv("fk_orders_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"], ["tables.id"], name=conv("fk_orders_table_id_tables"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["tab_id"], ["tabs.id"], name=conv("fk_orders_tab_id_tabs"), ondelete="RESTRICT"
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_orders_id_is_valid_ulid")),
        sa.CheckConstraint(
            "order_source IN ('pos', 'qr', 'delivery', 'takeaway')",
            name=conv("ck_orders_order_source_is_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'fired', 'served', 'billed', 'closed', 'voided')",
            name=conv("ck_orders_status_is_valid"),
        ),
        sa.CheckConstraint(
            "subtotal_amount >= 0", name=conv("ck_orders_subtotal_amount_is_non_negative")
        ),
        sa.CheckConstraint("tax_amount >= 0", name=conv("ck_orders_tax_amount_is_non_negative")),
        sa.CheckConstraint(
            "currency_code ~ '^[A-Z]{3}$'", name=conv("ck_orders_currency_code_is_iso4217")
        ),
    )
    op.create_index("ix_orders_tenant_id", "orders", ["tenant_id"])
    op.create_index("ix_orders_branch_id_status", "orders", ["branch_id", "status"])
    op.create_index("ix_orders_branch_id_opened_at", "orders", ["branch_id", "opened_at"])
    op.create_index("ix_orders_table_id", "orders", ["table_id"])
    op.create_index("ix_orders_tab_id", "orders", ["tab_id"])

    # --- order_items -----------------------------------------------------
    op.create_table(
        "order_items",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("order_id", sa.Text(), nullable=False),
        sa.Column("menu_item_id", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_amount", sa.Numeric(19, 4), nullable=False),
        sa.Column("modifiers_snapshot", sa.JSON(), nullable=False, server_default="[]"),
        sa.Column("recipe_cost_snapshot", sa.Numeric(19, 4), nullable=True),
        sa.Column("line_status", sa.Text(), nullable=False, server_default="added"),
        *_ts_immutable(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_order_items")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_order_items_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=conv("fk_order_items_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["menu_item_id"],
            ["menu_items.id"],
            name=conv("fk_order_items_menu_item_id_menu_items"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_order_items_id_is_valid_ulid")),
        sa.CheckConstraint("quantity > 0", name=conv("ck_order_items_quantity_is_positive")),
        sa.CheckConstraint(
            "unit_price_amount >= 0", name=conv("ck_order_items_unit_price_amount_is_non_negative")
        ),
        sa.CheckConstraint(
            "line_status IN ('added', 'fired', 'ready', 'served', 'voided')",
            name=conv("ck_order_items_line_status_is_valid"),
        ),
    )
    op.create_index("ix_order_items_tenant_id", "order_items", ["tenant_id"])
    op.create_index("ix_order_items_order_id", "order_items", ["order_id"])
    op.create_index("ix_order_items_menu_item_id", "order_items", ["menu_item_id"])

    # --- kitchen_tickets ---------------------------------------------------
    op.create_table(
        "kitchen_tickets",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("order_id", sa.Text(), nullable=False),
        sa.Column("station", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default="fired"),
        *_ts_immutable(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_kitchen_tickets")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_kitchen_tickets_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=conv("fk_kitchen_tickets_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_kitchen_tickets_id_is_valid_ulid")
        ),
        sa.CheckConstraint(
            "status IN ('fired', 'in_progress', 'ready', 'served')",
            name=conv("ck_kitchen_tickets_status_is_valid"),
        ),
    )
    op.create_index("ix_kitchen_tickets_tenant_id", "kitchen_tickets", ["tenant_id"])
    op.create_index("ix_kitchen_tickets_order_id", "kitchen_tickets", ["order_id"])

    # --- kitchen_items -------------------------------------------------------
    op.create_table(
        "kitchen_items",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("kitchen_ticket_id", sa.Text(), nullable=False),
        sa.Column("order_item_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default="queued"),
        *_ts_immutable(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_kitchen_items")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_kitchen_items_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["kitchen_ticket_id"],
            ["kitchen_tickets.id"],
            name=conv("fk_kitchen_items_kitchen_ticket_id_kitchen_tickets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["order_items.id"],
            name=conv("fk_kitchen_items_order_item_id_order_items"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_kitchen_items_id_is_valid_ulid")),
        sa.CheckConstraint(
            "status IN ('queued', 'in_progress', 'ready')",
            name=conv("ck_kitchen_items_status_is_valid"),
        ),
    )
    op.create_index("ix_kitchen_items_tenant_id", "kitchen_items", ["tenant_id"])
    op.create_index("ix_kitchen_items_kitchen_ticket_id", "kitchen_items", ["kitchen_ticket_id"])
    op.create_index("ix_kitchen_items_order_item_id", "kitchen_items", ["order_item_id"])

    # --- taxes -----------------------------------------------------------
    op.create_table(
        "taxes",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("rate", sa.Numeric(6, 4), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        *_ts_soft_delete(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_taxes")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_taxes_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_taxes_id_is_valid_ulid")),
        sa.CheckConstraint("rate >= 0 AND rate <= 1", name=conv("ck_taxes_rate_is_valid")),
    )
    op.create_index("ix_taxes_tenant_id", "taxes", ["tenant_id"])

    # --- discounts ---------------------------------------------------------
    op.create_table(
        "discounts",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("discount_type", sa.Text(), nullable=False),
        sa.Column("value", sa.Numeric(19, 4), nullable=False),
        sa.Column(
            "requires_approval", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column("max_value", sa.Numeric(19, 4), nullable=True),
        sa.Column("active_from", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("active_to", sa.TIMESTAMP(timezone=True), nullable=True),
        *_ts_soft_delete(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_discounts")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_discounts_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_discounts_id_is_valid_ulid")),
        sa.CheckConstraint(
            "discount_type IN ('percentage', 'fixed_amount')",
            name=conv("ck_discounts_discount_type_is_valid"),
        ),
        sa.CheckConstraint("value >= 0", name=conv("ck_discounts_value_is_non_negative")),
        sa.CheckConstraint(
            "active_from < active_to OR active_to IS NULL",
            name=conv("ck_discounts_active_window_is_valid"),
        ),
    )
    op.create_index("ix_discounts_tenant_id", "discounts", ["tenant_id"])

    # --- promo_codes -------------------------------------------------------
    op.create_table(
        "promo_codes",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("discount_id", sa.Text(), nullable=False),
        sa.Column("usage_limit", sa.Integer(), nullable=True),
        sa.Column("per_customer_limit", sa.Integer(), nullable=True),
        sa.Column("valid_from", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("valid_to", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=False, server_default="active"),
        *_ts_soft_delete(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_promo_codes")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_promo_codes_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["discount_id"],
            ["discounts.id"],
            name=conv("fk_promo_codes_discount_id_discounts"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_promo_codes_id_is_valid_ulid")),
        sa.CheckConstraint(
            "status IN ('active', 'exhausted', 'expired')",
            name=conv("ck_promo_codes_status_is_valid"),
        ),
    )
    op.create_index("ix_promo_codes_tenant_id", "promo_codes", ["tenant_id"])
    op.create_index("ix_promo_codes_discount_id", "promo_codes", ["discount_id"])
    op.create_index(
        "uq_promo_codes_tenant_id_code", "promo_codes", ["tenant_id", "code"], unique=True
    )

    # --- bills ---------------------------------------------------------------
    op.create_table(
        "bills",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("branch_id", sa.Text(), nullable=False),
        sa.Column("order_id", sa.Text(), nullable=True),
        sa.Column("tab_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False, server_default="open"),
        *_ts_immutable(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_bills")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_bills_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=conv("fk_bills_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=conv("fk_bills_order_id_orders"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["tab_id"], ["tabs.id"], name=conv("fk_bills_tab_id_tabs"), ondelete="RESTRICT"
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_bills_id_is_valid_ulid")),
        sa.CheckConstraint(
            "status IN ('open', 'partially_paid', 'closed')", name=conv("ck_bills_status_is_valid")
        ),
        # The XOR: a Bill closes out either exactly one Order or an
        # entire Tab, never both, never neither (Data Architecture v2.0
        # Group E).
        sa.CheckConstraint(
            "(order_id IS NOT NULL AND tab_id IS NULL) OR (order_id IS NULL AND tab_id IS NOT NULL)",
            name=conv("ck_bills_order_xor_tab"),
        ),
    )
    op.create_index("ix_bills_tenant_id", "bills", ["tenant_id"])
    op.create_index("ix_bills_branch_id", "bills", ["branch_id"])
    op.create_index("ix_bills_order_id", "bills", ["order_id"])
    op.create_index("ix_bills_tab_id", "bills", ["tab_id"])

    # --- bill_adjustments ------------------------------------------------
    # Unifies tips/service-charges/discounts/comps into one append-only
    # ledger (Data Architecture v2.0 Group B) -- no updated_at, applied
    # once, never edited.
    op.create_table(
        "bill_adjustments",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("bill_id", sa.Text(), nullable=False),
        sa.Column("adjustment_type", sa.Text(), nullable=False),
        sa.Column("reference_type", sa.Text(), nullable=True),
        sa.Column("reference_id", sa.Text(), nullable=True),
        sa.Column("amount", sa.Numeric(19, 4), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("approved_by_user_id", sa.Text(), nullable=True),
        *_ts_append_only(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_bill_adjustments")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_bill_adjustments_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bills.id"],
            name=conv("fk_bill_adjustments_bill_id_bills"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=conv("fk_bill_adjustments_approved_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_bill_adjustments_id_is_valid_ulid")
        ),
        sa.CheckConstraint(
            "adjustment_type IN ('discount', 'service_charge', 'tip', 'comp', 'write_off')",
            name=conv("ck_bill_adjustments_adjustment_type_is_valid"),
        ),
    )
    op.create_index("ix_bill_adjustments_tenant_id", "bill_adjustments", ["tenant_id"])
    op.create_index("ix_bill_adjustments_bill_id", "bill_adjustments", ["bill_id"])

    # --- order_tax_lines -----------------------------------------------
    op.create_table(
        "order_tax_lines",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("order_id", sa.Text(), nullable=False),
        sa.Column("tax_id", sa.Text(), nullable=False),
        sa.Column("taxable_amount", sa.Numeric(19, 4), nullable=False),
        sa.Column("tax_rate_snapshot", sa.Numeric(6, 4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(19, 4), nullable=False),
        *_ts_append_only(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_order_tax_lines")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_order_tax_lines_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=conv("fk_order_tax_lines_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tax_id"],
            ["taxes.id"],
            name=conv("fk_order_tax_lines_tax_id_taxes"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_order_tax_lines_id_is_valid_ulid")
        ),
        sa.CheckConstraint(
            "taxable_amount >= 0", name=conv("ck_order_tax_lines_taxable_amount_is_non_negative")
        ),
        sa.CheckConstraint(
            "tax_amount >= 0", name=conv("ck_order_tax_lines_tax_amount_is_non_negative")
        ),
    )
    op.create_index("ix_order_tax_lines_tenant_id", "order_tax_lines", ["tenant_id"])
    op.create_index("ix_order_tax_lines_order_id", "order_tax_lines", ["order_id"])

    # --- payments --------------------------------------------------------
    op.create_table(
        "payments",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("branch_id", sa.Text(), nullable=False),
        sa.Column("bill_id", sa.Text(), nullable=False),
        sa.Column("tender_type", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(19, 4), nullable=False),
        sa.Column("currency_code", sa.Text(), nullable=False),
        sa.Column("tip_amount", sa.Numeric(19, 4), nullable=False, server_default="0"),
        # PCI boundary: a passthrough reference only, never a raw card
        # number (Architecture doc SS3.4/SS2.1's own "out of scope" note
        # on real gateway integration).
        sa.Column("gateway_token_ref", sa.Text(), nullable=True),
        sa.Column("gateway_last4", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False, server_default="authorized"),
        *_ts_immutable(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_payments")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_payments_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=conv("fk_payments_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["bill_id"], ["bills.id"], name=conv("fk_payments_bill_id_bills"), ondelete="RESTRICT"
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_payments_id_is_valid_ulid")),
        sa.CheckConstraint(
            "tender_type IN ('cash', 'card', 'wallet')",
            name=conv("ck_payments_tender_type_is_valid"),
        ),
        sa.CheckConstraint("amount > 0", name=conv("ck_payments_amount_is_positive")),
        sa.CheckConstraint("tip_amount >= 0", name=conv("ck_payments_tip_amount_is_non_negative")),
        sa.CheckConstraint(
            "currency_code ~ '^[A-Z]{3}$'", name=conv("ck_payments_currency_code_is_iso4217")
        ),
        sa.CheckConstraint(
            "status IN ('authorized', 'captured', 'settled', 'declined')",
            name=conv("ck_payments_status_is_valid"),
        ),
    )
    op.create_index("ix_payments_tenant_id", "payments", ["tenant_id"])
    op.create_index("ix_payments_branch_id", "payments", ["branch_id"])
    op.create_index("ix_payments_bill_id", "payments", ["bill_id"])

    # --- refunds -----------------------------------------------------------
    op.create_table(
        "refunds",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("branch_id", sa.Text(), nullable=False),
        sa.Column("payment_id", sa.Text(), nullable=False),
        sa.Column("order_id", sa.Text(), nullable=False),
        # Every refund needs a named approver -- the only mechanism for
        # correcting a closed Order/Bill/Payment (Architecture doc SS3.4).
        sa.Column("approved_by_user_id", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(19, 4), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default="requested"),
        *_ts_immutable(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_refunds")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_refunds_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=conv("fk_refunds_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
            name=conv("fk_refunds_payment_id_payments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=conv("fk_refunds_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=conv("fk_refunds_approved_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_refunds_id_is_valid_ulid")),
        sa.CheckConstraint("amount > 0", name=conv("ck_refunds_amount_is_positive")),
        sa.CheckConstraint(
            "status IN ('requested', 'approved', 'processed')",
            name=conv("ck_refunds_status_is_valid"),
        ),
    )
    op.create_index("ix_refunds_tenant_id", "refunds", ["tenant_id"])
    op.create_index("ix_refunds_payment_id", "refunds", ["payment_id"])
    op.create_index("ix_refunds_order_id", "refunds", ["order_id"])

    # --- cash_drawers ------------------------------------------------------
    op.create_table(
        "cash_drawers",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("branch_id", sa.Text(), nullable=False),
        # Passthrough provenance only, no Terminal/Device entity yet
        # (Architecture doc SS2.1's own deferral).
        sa.Column("terminal_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False, server_default="open"),
        sa.Column("opening_float_amount", sa.Numeric(19, 4), nullable=False),
        sa.Column("closing_counted_amount", sa.Numeric(19, 4), nullable=True),
        sa.Column(
            "opened_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        *_ts_immutable(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_cash_drawers")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_cash_drawers_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=conv("fk_cash_drawers_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_cash_drawers_id_is_valid_ulid")),
        sa.CheckConstraint(
            "status IN ('open', 'closed')", name=conv("ck_cash_drawers_status_is_valid")
        ),
        sa.CheckConstraint(
            "opening_float_amount >= 0",
            name=conv("ck_cash_drawers_opening_float_amount_is_non_negative"),
        ),
    )
    op.create_index("ix_cash_drawers_tenant_id", "cash_drawers", ["tenant_id"])
    op.create_index("ix_cash_drawers_branch_id", "cash_drawers", ["branch_id"])

    # --- chart_of_accounts -------------------------------------------------
    # No tenant_id -- pure platform reference data, same classification
    # as `permissions` (see module docstring).
    op.create_table(
        "chart_of_accounts",
        sa.Column("account_code", sa.Text(), nullable=False),
        sa.Column("account_name", sa.Text(), nullable=False),
        sa.Column("account_type", sa.Text(), nullable=False),
        *_ts_immutable(),
        sa.PrimaryKeyConstraint("account_code", name=conv("pk_chart_of_accounts")),
        sa.CheckConstraint(
            "account_type IN ('asset', 'liability', 'revenue', 'expense', 'equity')",
            name=conv("ck_chart_of_accounts_account_type_is_valid"),
        ),
    )

    # --- ledger_entries ------------------------------------------------
    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("entry_type", sa.Text(), nullable=False),
        sa.Column("account_code", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(19, 4), nullable=False),
        sa.Column("currency_code", sa.Text(), nullable=False),
        sa.Column("reference_type", sa.Text(), nullable=True),
        sa.Column("reference_id", sa.Text(), nullable=True),
        *_ts_append_only(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_ledger_entries")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_ledger_entries_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["account_code"],
            ["chart_of_accounts.account_code"],
            name=conv("fk_ledger_entries_account_code_chart_of_accounts"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_ledger_entries_id_is_valid_ulid")
        ),
        sa.CheckConstraint(
            "entry_type IN ('debit', 'credit')", name=conv("ck_ledger_entries_entry_type_is_valid")
        ),
        sa.CheckConstraint("amount > 0", name=conv("ck_ledger_entries_amount_is_positive")),
        sa.CheckConstraint(
            "currency_code ~ '^[A-Z]{3}$'", name=conv("ck_ledger_entries_currency_code_is_iso4217")
        ),
    )
    op.create_index("ix_ledger_entries_tenant_id", "ledger_entries", ["tenant_id"])
    op.create_index("ix_ledger_entries_account_code", "ledger_entries", ["account_code"])
    op.create_index(
        "ix_ledger_entries_reference_type_reference_id",
        "ledger_entries",
        ["reference_type", "reference_id"],
    )

    # --- inventory_categories ------------------------------------------
    op.create_table(
        "inventory_categories",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        *_ts_soft_delete(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_inventory_categories")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_inventory_categories_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_inventory_categories_id_is_valid_ulid")
        ),
    )
    op.create_index("ix_inventory_categories_tenant_id", "inventory_categories", ["tenant_id"])
    op.create_index(
        "uq_inventory_categories_tenant_id_name",
        "inventory_categories",
        ["tenant_id", "name"],
        unique=True,
    )

    # --- inventory_items -------------------------------------------------
    op.create_table(
        "inventory_items",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("branch_id", sa.Text(), nullable=False),
        sa.Column("inventory_category_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("unit", sa.Text(), nullable=False),
        # Derived/cached -- maintained exclusively by the
        # enforce_stock_movement_and_update_balance() trigger below,
        # never hand-written by application code (Data Architecture v2.0
        # Group D; Architecture doc SS3.6).
        sa.Column("quantity_on_hand", sa.Numeric(14, 4), nullable=False, server_default="0"),
        sa.Column("reorder_point", sa.Numeric(14, 4), nullable=True),
        sa.Column("allow_negative_stock_override", sa.Boolean(), nullable=True),
        *_ts_soft_delete(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_inventory_items")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_inventory_items_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=conv("fk_inventory_items_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["inventory_category_id"],
            ["inventory_categories.id"],
            name=conv("fk_inventory_items_inventory_category_id_inventory_categories"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_inventory_items_id_is_valid_ulid")
        ),
        sa.CheckConstraint(
            "reorder_point IS NULL OR reorder_point >= 0",
            name=conv("ck_inventory_items_reorder_point_is_non_negative"),
        ),
    )
    op.create_index("ix_inventory_items_tenant_id", "inventory_items", ["tenant_id"])
    op.create_index("ix_inventory_items_branch_id", "inventory_items", ["branch_id"])
    op.create_index(
        "ix_inventory_items_inventory_category_id", "inventory_items", ["inventory_category_id"]
    )
    op.create_index(
        "uq_inventory_items_branch_id_name", "inventory_items", ["branch_id", "name"], unique=True
    )

    # --- recipes -------------------------------------------------------------
    op.create_table(
        "recipes",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        # Self-referencing -- editing a recipe creates a new row and
        # repoints menu_items.recipe_id, never edits history in place
        # (Architecture doc SS3.6).
        sa.Column("superseded_by_id", sa.Text(), nullable=True),
        *_ts_soft_delete(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_recipes")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_recipes_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["recipes.id"],
            name=conv("fk_recipes_superseded_by_id_recipes"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_recipes_id_is_valid_ulid")),
        sa.CheckConstraint("version > 0", name=conv("ck_recipes_version_is_positive")),
    )
    op.create_index("ix_recipes_tenant_id", "recipes", ["tenant_id"])

    # --- recipe_ingredients ------------------------------------------------
    op.create_table(
        "recipe_ingredients",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("recipe_id", sa.Text(), nullable=False),
        sa.Column("inventory_item_id", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(12, 4), nullable=False),
        sa.Column("unit", sa.Text(), nullable=False),
        *_ts_immutable(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_recipe_ingredients")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_recipe_ingredients_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=conv("fk_recipe_ingredients_recipe_id_recipes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=conv("fk_recipe_ingredients_inventory_item_id_inventory_items"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_recipe_ingredients_id_is_valid_ulid")
        ),
        sa.CheckConstraint("quantity > 0", name=conv("ck_recipe_ingredients_quantity_is_positive")),
    )
    op.create_index("ix_recipe_ingredients_tenant_id", "recipe_ingredients", ["tenant_id"])
    op.create_index("ix_recipe_ingredients_recipe_id", "recipe_ingredients", ["recipe_id"])
    op.create_index(
        "ix_recipe_ingredients_inventory_item_id", "recipe_ingredients", ["inventory_item_id"]
    )

    # --- stock_movements -----------------------------------------------
    # The append-only ledger -- inventory_items.quantity_on_hand is
    # derived from this table by the trigger below, never written
    # directly (Data Architecture v2.0 Group D).
    op.create_table(
        "stock_movements",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("branch_id", sa.Text(), nullable=False),
        sa.Column("inventory_item_id", sa.Text(), nullable=False),
        sa.Column("movement_type", sa.Text(), nullable=False),
        sa.Column("quantity_delta", sa.Numeric(14, 4), nullable=False),
        sa.Column("reference_type", sa.Text(), nullable=True),
        sa.Column("reference_id", sa.Text(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        *_ts_append_only(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_stock_movements")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_stock_movements_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=conv("fk_stock_movements_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=conv("fk_stock_movements_inventory_item_id_inventory_items"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_stock_movements_id_is_valid_ulid")
        ),
        sa.CheckConstraint(
            "movement_type IN ('sale_deduction', 'adjustment', 'receipt', 'waste', 'transfer')",
            name=conv("ck_stock_movements_movement_type_is_valid"),
        ),
        sa.CheckConstraint(
            "quantity_delta <> 0", name=conv("ck_stock_movements_quantity_delta_is_nonzero")
        ),
    )
    op.create_index("ix_stock_movements_tenant_id", "stock_movements", ["tenant_id"])
    op.create_index("ix_stock_movements_branch_id", "stock_movements", ["branch_id"])
    op.create_index(
        "ix_stock_movements_inventory_item_id_occurred_at",
        "stock_movements",
        ["inventory_item_id", "occurred_at"],
    )
    op.create_index(
        "uq_stock_movements_tenant_id_idempotency_key",
        "stock_movements",
        ["tenant_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )

    # --- stock_adjustments -----------------------------------------------
    op.create_table(
        "stock_adjustments",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("branch_id", sa.Text(), nullable=False),
        sa.Column("inventory_item_id", sa.Text(), nullable=False),
        sa.Column("stock_movement_id", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("approved_by_user_id", sa.Text(), nullable=False),
        *_ts_immutable(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_stock_adjustments")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_stock_adjustments_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=conv("fk_stock_adjustments_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=conv("fk_stock_adjustments_inventory_item_id_inventory_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stock_movement_id"],
            ["stock_movements.id"],
            name=conv("fk_stock_adjustments_stock_movement_id_stock_movements"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=conv("fk_stock_adjustments_approved_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_stock_adjustments_id_is_valid_ulid")
        ),
    )
    op.create_index("ix_stock_adjustments_tenant_id", "stock_adjustments", ["tenant_id"])
    op.create_index("ix_stock_adjustments_branch_id", "stock_adjustments", ["branch_id"])
    op.create_index(
        "ix_stock_adjustments_inventory_item_id", "stock_adjustments", ["inventory_item_id"]
    )

    # --- suppliers -----------------------------------------------------
    # Tenant-level, NOT branch-scoped -- a supplier typically serves
    # every branch of a tenant (Architecture doc SS2.1/SS3.7).
    op.create_table(
        "suppliers",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("address_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False, server_default="active"),
        *_ts_soft_delete(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_suppliers")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_suppliers_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["addresses.id"],
            name=conv("fk_suppliers_address_id_addresses"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(f"id ~ '{_ULID_REGEX}'", name=conv("ck_suppliers_id_is_valid_ulid")),
        sa.CheckConstraint(
            "status IN ('active', 'inactive')", name=conv("ck_suppliers_status_is_valid")
        ),
    )
    op.create_index("ix_suppliers_tenant_id", "suppliers", ["tenant_id"])
    op.create_index("uq_suppliers_tenant_id_name", "suppliers", ["tenant_id", "name"], unique=True)

    # --- purchase_orders -------------------------------------------------
    op.create_table(
        "purchase_orders",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("branch_id", sa.Text(), nullable=False),
        sa.Column("supplier_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default="draft"),
        *_ts_immutable(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_purchase_orders")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_purchase_orders_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=conv("fk_purchase_orders_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=conv("fk_purchase_orders_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_purchase_orders_id_is_valid_ulid")
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'sent', 'partially_received', 'fully_received', 'canceled')",
            name=conv("ck_purchase_orders_status_is_valid"),
        ),
    )
    op.create_index("ix_purchase_orders_tenant_id", "purchase_orders", ["tenant_id"])
    op.create_index("ix_purchase_orders_branch_id", "purchase_orders", ["branch_id"])
    op.create_index("ix_purchase_orders_supplier_id", "purchase_orders", ["supplier_id"])

    # --- purchase_order_items ---------------------------------------------
    op.create_table(
        "purchase_order_items",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("purchase_order_id", sa.Text(), nullable=False),
        sa.Column("inventory_item_id", sa.Text(), nullable=False),
        sa.Column("quantity_ordered", sa.Numeric(14, 4), nullable=False),
        sa.Column("quantity_received", sa.Numeric(14, 4), nullable=False, server_default="0"),
        *_ts_immutable(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_purchase_order_items")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_purchase_order_items_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=conv("fk_purchase_order_items_purchase_order_id_purchase_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=conv("fk_purchase_order_items_inventory_item_id_inventory_items"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_purchase_order_items_id_is_valid_ulid")
        ),
        sa.CheckConstraint(
            "quantity_ordered > 0",
            name=conv("ck_purchase_order_items_quantity_ordered_is_positive"),
        ),
        sa.CheckConstraint(
            "quantity_received >= 0",
            name=conv("ck_purchase_order_items_quantity_received_is_non_negative"),
        ),
    )
    op.create_index("ix_purchase_order_items_tenant_id", "purchase_order_items", ["tenant_id"])
    op.create_index(
        "ix_purchase_order_items_purchase_order_id", "purchase_order_items", ["purchase_order_id"]
    )
    op.create_index(
        "ix_purchase_order_items_inventory_item_id", "purchase_order_items", ["inventory_item_id"]
    )

    # --- goods_receipts ------------------------------------------------
    op.create_table(
        "goods_receipts",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("purchase_order_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default="created"),
        sa.Column(
            "received_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("has_discrepancy", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        *_ts_immutable(),
        sa.PrimaryKeyConstraint("id", name=conv("pk_goods_receipts")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=conv("fk_goods_receipts_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=conv("fk_goods_receipts_purchase_order_id_purchase_orders"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"id ~ '{_ULID_REGEX}'", name=conv("ck_goods_receipts_id_is_valid_ulid")
        ),
        sa.CheckConstraint(
            "status IN ('created', 'confirmed')", name=conv("ck_goods_receipts_status_is_valid")
        ),
    )
    op.create_index("ix_goods_receipts_tenant_id", "goods_receipts", ["tenant_id"])
    op.create_index("ix_goods_receipts_purchase_order_id", "goods_receipts", ["purchase_order_id"])

    # --- updated_at triggers (reuses set_updated_at() from 0001) -------------
    for table in _TIMESTAMPED_TABLES:
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_set_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            EXECUTE FUNCTION set_updated_at();
            """
        )

    # --- Row-Level Security ---------------------------------------------------
    for table in _TENANT_SCOPED_RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (tenant_id = current_setting('app.tenant_id', true))
            """
        )
    # chart_of_accounts: no RLS -- pure platform reference data, see
    # module docstring.

    # --- negative-inventory enforcement + quantity_on_hand maintenance ------
    # One combined trigger (Data Architecture v2.0 Group D): a CHECK
    # constraint cannot aggregate sibling rows, so the balance check and
    # the balance update both live here, in the same BEFORE INSERT pass.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION enforce_stock_movement_and_update_balance()
        RETURNS TRIGGER AS $$
        DECLARE
            current_qty NUMERIC(14, 4);
            resulting_qty NUMERIC(14, 4);
            item_override BOOLEAN;
            branch_allows_negative BOOLEAN;
        BEGIN
            SELECT quantity_on_hand, allow_negative_stock_override
              INTO current_qty, item_override
              FROM inventory_items
              WHERE id = NEW.inventory_item_id
              FOR UPDATE;

            resulting_qty := current_qty + NEW.quantity_delta;

            IF resulting_qty < 0 THEN
                SELECT allow_negative_stock INTO branch_allows_negative
                  FROM branches WHERE id = NEW.branch_id;

                IF NOT COALESCE(item_override, branch_allows_negative, false) THEN
                    RAISE EXCEPTION
                        'stock movement would take inventory_item % negative (current % + delta % = %)',
                        NEW.inventory_item_id, current_qty, NEW.quantity_delta, resulting_qty;
                END IF;
            END IF;

            UPDATE inventory_items SET quantity_on_hand = resulting_qty WHERE id = NEW.inventory_item_id;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_stock_movements_enforce_and_update_balance
        BEFORE INSERT ON stock_movements
        FOR EACH ROW
        EXECUTE FUNCTION enforce_stock_movement_and_update_balance();
        """
    )

    # --- seed data: chart of accounts -----------------------------------
    chart_of_accounts_table = sa.table(
        "chart_of_accounts",
        sa.column("account_code", sa.Text()),
        sa.column("account_name", sa.Text()),
        sa.column("account_type", sa.Text()),
    )
    op.bulk_insert(
        chart_of_accounts_table,
        [
            {"account_code": code, "account_name": name, "account_type": account_type}
            for code, name, account_type in _SEED_CHART_OF_ACCOUNTS
        ],
    )

    # --- seed data: new permissions (appended to the existing table) ------
    permissions_table = sa.table(
        "permissions",
        sa.column("code", sa.Text()),
        sa.column("module", sa.Text()),
        sa.column("description", sa.Text()),
    )
    op.bulk_insert(
        permissions_table,
        [
            {"code": code, "module": module, "description": description}
            for code, module, description in _SEED_PERMISSIONS
        ],
    )


def downgrade() -> None:
    op.execute(
        "DELETE FROM permissions WHERE code IN ("
        + ", ".join(f"'{code}'" for code, _, _ in _SEED_PERMISSIONS)
        + ")"
    )

    op.execute(
        "DROP TRIGGER IF EXISTS trg_stock_movements_enforce_and_update_balance ON stock_movements"
    )
    op.execute("DROP FUNCTION IF EXISTS enforce_stock_movement_and_update_balance()")

    for table in _TENANT_SCOPED_RLS_TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    for table in _TIMESTAMPED_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_set_updated_at ON {table}")

    # Drop in FK-dependency order: children before parents.
    op.drop_table("goods_receipts")
    op.drop_table("purchase_order_items")
    op.drop_table("purchase_orders")
    op.drop_table("suppliers")
    op.drop_table("stock_adjustments")
    op.drop_table("stock_movements")
    op.drop_table("recipe_ingredients")
    op.drop_table("recipes")
    op.drop_table("inventory_items")
    op.drop_table("inventory_categories")
    op.drop_table("ledger_entries")
    op.drop_table("chart_of_accounts")
    op.drop_table("cash_drawers")
    op.drop_table("refunds")
    op.drop_table("payments")
    op.drop_table("order_tax_lines")
    op.drop_table("bill_adjustments")
    op.drop_table("bills")
    op.drop_table("promo_codes")
    op.drop_table("discounts")
    op.drop_table("taxes")
    op.drop_table("kitchen_items")
    op.drop_table("kitchen_tickets")
    op.drop_table("order_items")
    op.drop_table("orders")
    op.drop_table("tabs")

    op.drop_column("branches", "allow_negative_stock")
