/**
 * Mirrors services/api/src/restaurant_os_api/platform/currencies.py's
 * ISO_4217_CURRENCIES exactly -- TypeScript can't import a Python
 * module, so this is kept in sync by hand. Keep both in sync if this
 * one ever changes (ISO 4217 itself changes rarely, so this should be
 * uncommon).
 *
 * A tenant was created with defaultCurrencyCode = "GST" -- not a
 * currency, a tax -- because the form was free text checked only for
 * "3 uppercase letters". This is the real list backing both this
 * form's dropdown and (mirrored on the backend) the API's own
 * validation, so neither can be bypassed independently. See the Python
 * module's own docstring for the full reasoning behind which 11 real
 * ISO 4217 codes are deliberately excluded (precious metals, the IMF's
 * XDR, defunct bond-market composite units, and the two codes the
 * standard itself defines as non-currencies).
 */
export const ISO_4217_CURRENCIES: Record<string, string> = {
  AED: "United Arab Emirates dirham",
  AFN: "Afghan afghani",
  ALL: "Albanian lek",
  AMD: "Armenian dram",
  AOA: "Angolan kwanza",
  ARS: "Argentine peso",
  AUD: "Australian dollar",
  AWG: "Aruban florin",
  AZN: "Azerbaijani manat",
  BAM: "Bosnia and Herzegovina convertible mark",
  BBD: "Barbados dollar",
  BDT: "Bangladeshi taka",
  BHD: "Bahraini dinar",
  BIF: "Burundian franc",
  BMD: "Bermudian dollar",
  BND: "Brunei dollar",
  BOB: "Boliviano",
  BOV: "Bolivian Mvdol",
  BRL: "Brazilian real",
  BSD: "Bahamian dollar",
  BTN: "Bhutanese ngultrum",
  BWP: "Botswana pula",
  BYN: "Belarusian ruble",
  BZD: "Belize dollar",
  CAD: "Canadian dollar",
  CDF: "Congolese franc",
  CHE: "WIR euro",
  CHF: "Swiss franc",
  CHW: "WIR franc",
  CLF: "Unidad de Fomento",
  CLP: "Chilean peso",
  CNY: "Renminbi",
  COP: "Colombian peso",
  COU: "Unidad de Valor Real",
  CRC: "Costa Rican colon",
  CUP: "Cuban peso",
  CVE: "Cape Verdean escudo",
  CZK: "Czech koruna",
  DJF: "Djiboutian franc",
  DKK: "Danish krone",
  DOP: "Dominican peso",
  DZD: "Algerian dinar",
  EGP: "Egyptian pound",
  ERN: "Eritrean nakfa",
  ETB: "Ethiopian birr",
  EUR: "Euro",
  FJD: "Fiji dollar",
  FKP: "Falkland Islands pound",
  GBP: "Pound sterling",
  GEL: "Georgian lari",
  GHS: "Ghanaian cedi",
  GIP: "Gibraltar pound",
  GMD: "Gambian dalasi",
  GNF: "Guinean franc",
  GTQ: "Guatemalan quetzal",
  GYD: "Guyanese dollar",
  HKD: "Hong Kong dollar",
  HNL: "Honduran lempira",
  HTG: "Haitian gourde",
  HUF: "Hungarian forint",
  IDR: "Indonesian rupiah",
  ILS: "Israeli new shekel",
  INR: "Indian rupee",
  IQD: "Iraqi dinar",
  IRR: "Iranian rial",
  ISK: "Icelandic krona",
  JMD: "Jamaican dollar",
  JOD: "Jordanian dinar",
  JPY: "Japanese yen",
  KES: "Kenyan shilling",
  KGS: "Kyrgyzstani som",
  KHR: "Cambodian riel",
  KMF: "Comoro franc",
  KPW: "North Korean won",
  KRW: "South Korean won",
  KWD: "Kuwaiti dinar",
  KYD: "Cayman Islands dollar",
  KZT: "Kazakhstani tenge",
  LAK: "Lao kip",
  LBP: "Lebanese pound",
  LKR: "Sri Lankan rupee",
  LRD: "Liberian dollar",
  LSL: "Lesotho loti",
  LYD: "Libyan dinar",
  MAD: "Moroccan dirham",
  MDL: "Moldovan leu",
  MGA: "Malagasy ariary",
  MKD: "Macedonian denar",
  MMK: "Myanmar kyat",
  MNT: "Mongolian togrog",
  MOP: "Macanese pataca",
  MRU: "Mauritanian ouguiya",
  MUR: "Mauritian rupee",
  MVR: "Maldivian rufiyaa",
  MWK: "Malawian kwacha",
  MXN: "Mexican peso",
  MXV: "Mexican Unidad de Inversion",
  MYR: "Malaysian ringgit",
  MZN: "Mozambican metical",
  NAD: "Namibian dollar",
  NGN: "Nigerian naira",
  NIO: "Nicaraguan cordoba",
  NOK: "Norwegian krone",
  NPR: "Nepalese rupee",
  NZD: "New Zealand dollar",
  OMR: "Omani rial",
  PAB: "Panamanian balboa",
  PEN: "Peruvian sol",
  PGK: "Papua New Guinean kina",
  PHP: "Philippine peso",
  PKR: "Pakistani rupee",
  PLN: "Polish zloty",
  PYG: "Paraguayan guarani",
  QAR: "Qatari riyal",
  RON: "Romanian leu",
  RSD: "Serbian dinar",
  RUB: "Russian ruble",
  RWF: "Rwandan franc",
  SAR: "Saudi riyal",
  SBD: "Solomon Islands dollar",
  SCR: "Seychelles rupee",
  SDG: "Sudanese pound",
  SEK: "Swedish krona",
  SGD: "Singapore dollar",
  SHP: "Saint Helena pound",
  SLE: "Sierra Leonean leone",
  SOS: "Somali shilling",
  SRD: "Surinamese dollar",
  SSP: "South Sudanese pound",
  STN: "Sao Tome and Principe dobra",
  SVC: "Salvadoran colon",
  SYP: "Syrian pound",
  SZL: "Swazi lilangeni",
  THB: "Thai baht",
  TJS: "Tajikistani somoni",
  TMT: "Turkmenistan manat",
  TND: "Tunisian dinar",
  TOP: "Tongan pa'anga",
  TRY: "Turkish lira",
  TTD: "Trinidad and Tobago dollar",
  TWD: "New Taiwan dollar",
  TZS: "Tanzanian shilling",
  UAH: "Ukrainian hryvnia",
  UGX: "Ugandan shilling",
  USD: "United States dollar",
  USN: "United States dollar (next day)",
  UYI: "Uruguay Peso en Unidades Indexadas",
  UYU: "Uruguayan peso",
  UYW: "Unidad previsional",
  UZS: "Uzbekistani sum",
  VED: "Venezuelan digital bolivar",
  VES: "Venezuelan sovereign bolivar",
  VND: "Vietnamese dong",
  VUV: "Vanuatu vatu",
  WST: "Samoan tala",
  XAF: "CFA franc BEAC",
  XCD: "East Caribbean dollar",
  XOF: "CFA franc BCEAO",
  XPF: "CFP franc",
  XSU: "Sucre",
  YER: "Yemeni rial",
  ZAR: "South African rand",
  ZMW: "Zambian kwacha",
  ZWL: "Zimbabwean dollar",
}
